### DISCUSSION TITLE
Load plugin from github

### DISCUSSION THREAD

**Discussion by mr-loop-1** [Green-Software-Foundation/if#581] [Q&A] [answered]
I was reading this page https://if.greensoftware.foundation/users/how-to-import-plugins in the docs and noticed that there is some way that plugins can be loaded directly from a github repo of a user.
I tried to do that with the unofficial-plugins repo but I am not able to make it work.

For example, if I want to load the `teads-aws` plugin from [here](https://github.com/Green-Software-Foundation/if-unofficial-plugins/blob/main/src/lib/teads-aws) instead of installing from npm, then what exactly should I put in the `path` property in manifest?

**Comment by mgriffin-scottlogic** [comment, marked as answer]
The Readme for https://github.com/Green-Software-Foundation/if-plugin-template has some good information on this. You still need an npm install but you use the github repo path instead of a package name:
```
npm install -g https://github.com/Green-Software-Foundation/if-unofficial-plugins
```
Then the manifest should be set like:
```yml
name: plugin-demo-git
description: loads plugin
tags: null
initialize:
  plugins:
    teads-aws:
      method: TeadsAWS
      path: https://github.com/Green-Software-Foundation/if-unofficial-plugins
      global-config:
        ...
...
```
