### ISSUE TITLE
Check if the manifest is already grouped

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1041]
**Why**:
To resolve errors in `if-check` script and prevent error in edge case where user regroups an already-grouped manifest.

**What**: 

Add a check to see if the manifest is already grouped according to the config. If the manifest is already grouped according to the given config, we should simply skip the `regroup` step.

The current behaviour, that we want to fix, is that the manifest `regroup` feature executes even the manifest is already grouped, which leads to additional, unnecessary levels of nesting.

**Scope of work:**
- [ ] implement acceptance criteria
- [ ] test cases added

### Scenario 1: 

The following manifest:

```yaml
# start
name: regroup
description: successful path
initialize:
  plugins: {}
tree:
  children:
    my-app:
      pipeline:
        regroup:
          - cloud/region
          - cloud/instance-type
      children:
        uk-west:
          children:
            A1:
              inputs:
                - timestamp: 2023-07-06T00:00
                  duration: 300
                  cloud/instance-type: A1
                  cloud/region: uk-west
                  cpu/utilization: 99
                - timestamp: 2023-07-06T05:00
                  duration: 300
                  cloud/instance-type: A1
                  cloud/region: uk-west
                  cpu/utilization: 23
                - timestamp: 2023-07-06T10:00
                  duration: 300
                  cloud/instance-type: A1
                  cloud/region: uk-west
                  cpu/utilization: 12
            B1:
              inputs:
                - timestamp: 2023-07-06T00:00
                  duration: 300
                  cloud/instance-type: B1
                  cloud/region: uk-west
                  cpu/utilization: 11
                - timestamp: 2023-07-06T05:00
                  duration: 300
                  cloud/instance-type: B1
                  cloud/region: uk-west
                  cpu/utilization: 67
                - timestamp: 2023-07-06T10:00
                  duration: 300
                  cloud/instance-type: B1
                  cloud/region: uk-west
                  cpu/utilization: 1

```

Should return the same exact file when run using `if-run --regroup -m <manifest>` (except for adding an execution node to `context`)
