### ISSUE TITLE
Add csv-import plugin to builtins

### ISSUE THREAD

**Issue by bvickers7** [Green-Software-Foundation/if#1051]
**What**
A builtin plugin that imports observations from a CSV file. Each row in the CSV is mapped to an input in the manifest.

**Why**
Inputs can have many data points and for data sources that do not have dedicated importer plugins, a generic CSV import utility would save time by offering an alternative to manually copying in data points to the input.

**Context**
- The `csv-lookup` builtin plugin exists. This is different from that. `csv-lookup` adds data to existing inputs by matching existing values in the inputs to rows in the CSV file. `csv-import` should generate a list of inputs, where each row is an input.
- Some discussion around this feature has already happened in https://github.com/Green-Software-Foundation/if/issues/780#issuecomment-2155061058 

**Prerequisites/resources**
None

**SoW (scope of work)**

- [x] new directory in [builtins](https://github.com/Green-Software-Foundation/if/tree/main/src/if-run/builtins) with implementation
- [x] test cases added
- [x] README in new directory documenting plugin usage

**Acceptance criteria**

- [x] Scenario 1: Import from local file

**Given** I have a CSV file with the following data at `/path/to/my/file.csv`
timestamp | duration | cpu-util | energy
-- | -- | -- | --
2023-07-06T00:00 | 1 | 20 | 5
2023-07-06T00:01 | 1 | 30 | 10
2023-07-06T00:02 | 1 | 40 | 15

**When**  I add the following to my manifest:
```
  plugins:
    data-import:
      method: CSVImport
      path: 'builtin'
      config:
        filepath: /path/to/my/file.csv
        output: '*'
```

**Then** the plugin has the following output:
```
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu-util: 20
          energy: 5
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu-util: 30
          energy: 10
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu-util: 40
          energy: 15
```

- [x] Scenario 2: Import from a URL

**Given** I have the same data from scenario 1 available to the public internet at `https://mywebsite.com/file.csv`
**When**  I add the same block from scenario 1 to my manifest, except with `filepath: https://mywebsite.com/file.csv`
**Then** the plugin has the same output as scenario 1

- [x] Scenario 3: Selecting and Renaming Columns
**Given** I have the same file from scenario 1
**When**  I add the following block to my manifest
```
  plugins:
    data-import:
      method: CSVImport
      path: 'builtin'
      config:
        filepath: /path/to/my/file.csv
        output: [ ['timestamp'], ['duration'], ['cpu-util', 'cpu/utilization'] ]
```

**Then** the plugin has the following output:
```
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 30
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 40
```
This format for the `output` config was selected to be consistent with the [csv-lookup plugin](https://github.com/Green-Software-Foundation/if/tree/main/src/if-run/builtins/csv-lookup#plugin-config). I think this is not the simplest way to structure this config, and would like to discuss if complicating the config is worth keeping things consistent between plugins.

It should accept the following:
- '*' indicating all columns should be selected
- 'foo' indicating that only column 'foo' should be selected
- ['foo', 'bar'] indicating that only column 'foo' should be selected and output as 'bar
- [ ['foo', 'bar'], ['bat'] ] indicating that the 'foo' and 'bat' columns should be selected with 'foo' output as 'bar'
