### ISSUE TITLE
Information about defaults and inputs

### ISSUE THREAD

**Issue by tdigeser91** [Green-Software-Foundation/if#1073]
Do you have some informations about the defaults and inputs used in the manifests?

**Comment by jmcook1186** [comment]
hi @tdigeser91 sorry for the delayed reply. `Inputs` are the required set of data that each component in your manifest must have. All plugins take data from `inputs` and enrich or transform them somehow to generate `outputs`.

Defaults are a convenience tool that inserts values into `inputs` at runtime. For example, if you have a constant that you want to include in every element in your `inputs` but you don't want to haveto manually copy the key/value pair into every element in your `inputs`, you can add it once to the `defaults` section and IF will automatically copy it into every element in `inputs`.

So, the two following examples are functionally equivalent:

1) `some-value` is in `inputs`

```yaml
inputs:
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
    some-value: 45
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
    some-value: 45
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
    some-value: 45
```

2) `some-value` is in `defaults`

```yaml
defaults:
  some-value: 45
inputs:
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
  - timestamp: 2024-08-06...
    duration: 3600
    cpu: 65
    memory: 5
```
