### ISSUE TITLE
Add energy-consumption-calculator plugin to builtins

### ISSUE THREAD

**Issue by kaito-kameda** [Green-Software-Foundation/if#1111]
**What**
A builtin plugin that calculates energy consumption from wattage and duration. 

**Why**
The calculation of SCI score requires energy consumption. However, in many cases, the data obtained from the machine in use is wattage, so it is necessary to calculate energy consumption based on wattage and duration. This is a common calculation, but currently it is calculated using two plugins, 'multiply' and 'divide', which is a bit cumbersome. Creating a plugin that directly calculates energy consumption from wattage and duration would allow the manifest to be written more concisely.

**Context**

**Prerequisites/resources**
None

**SoW (scope of work)**
- [ ] new directory in builtins with implementation
- [ ] test cases added
- [ ] README in new directory documenting plugin usage

**Acceptance criteria**
- [ ] plugin calculates energy consumption from given wattage and duration

**Given** the plugin works as intended
**When** I run the following manifest

```yaml
name: energy-consumption-calculater demo
description: successful path
tags:
initialize:
  plugins:
    calculateEnergyConsumption:
      method: CalculateEnergyConsumption
      path: "builtin"
      config:
        input-parameter: "wattage"
        output-parameter: "energy-consumption"
tree:
  children:
    child:
      pipeline:
        compute:
          - calculateEnergyConsumption
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          wattage: 100
```

**Then** I get the following output:

```yaml
name: energy-consumption-calculater demo
description: successful path
tags:
initialize:
  plugins:
    calculateEnergyConsumption:
      method: CalculateEnergyConsumption
      path: "builtin"
      config:
        input-parameter: "wattage"
        output-parameter: "energy-consumption"
tree:
  children:
    child:
      pipeline:
        compute:
          - calculateEnergyConsumption
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          wattage: 100
          energy-consumption: 0.1
```
