### ISSUE TITLE
Defaults not merged on imported Inputs

### ISSUE THREAD

**Issue by imix** [Green-Software-Foundation/if#1114]
## Description of the Error
When importing Inputs with the CSVImporter plugin, the Inputs are added to the list of inputs. Values specified in the "defaults" section are NOT merged with the values from the loaded csv. Furthermore a "dummy" empty Input is prepended to the loaded inputs.

## Expected Behaviour
Defaults are merged in all inputs, regardless whether they are in the manifest or loaded from an external source. No additional line inserted.

The output section should look like this:

```
      outputs:
        - timestamp: '2023-12-12T00:00:15.000Z'
          random: default
          some/type: another
        - timestamp: '2023-12-12T00:00:17.000Z'
          random: default
          some/type: another
```

## Actual Behaviour
At least for the CSVImporter plugin, the defaults are not merged. An addidional input is inserted before the inputs loaded from the CSV.

The outputs look like this:

```
      outputs:
        - random: default
          some/type: another
        - timestamp: '2023-12-12T00:00:15.000Z'
        - timestamp: '2023-12-12T00:00:17.000Z'

```

## Steps to Reproduce
Run the manifest file below with the csv in the same folder.

## Link to online environment
- 

## Manifest File That Generated the Error

```
name: csv-load-test
tags:
explainer: true
initialize:
  plugins:
    load-data:
      method: CSVImport
      path: 'builtin'
      config:
        filepath: ./load.csv
        output: "*"
tree:
  children:
    child:
      pipeline:
        observe:
          - load-data
        regroup:
        compute:
      defaults:
        random: 'default'
        some/type: 'another'
      inputs:

```
## Links to Any Additional Code
load.csv:

timestamp
2023-12-12T00:00:15.000Z
2023-12-12T00:00:17.000Z

## Runtime Info
OS: windows 11
node: v18.20.5
if: @grnsft/if@1.0.0
