### ISSUE TITLE
Model Plugin - Azure Importer

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#129]
- **What**: An exporter which returns a series of observations from Azure Monitor
- **Why**: So we can easily export observations for use by models
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Is the code documented?

## Config
- N/A (some authentication information but it will be in the form of env vars)

## Observation
- `subscription-id`: The subscription id to export data from
- `resource-group`: The subscription id to export data from
- `name`: The name to export data from
- `tags`: The tags to export data from
- `timestamp`: start time of the export
- `duration`: how long from the start time do you want to run the export for.
- `observation-window`: how much time in each observation window, e.g. do you want to export multiple observations with 5 min windows

## Impacts
_List the variables this model exports out as an impact_
- `ram-alloc`: GB of memory allocated.
- `gpu-util`: %age utilization of the GPU
- `cpu-util`: %age utilization of the CPU
- `instance-type`: ??? the azure instance name, not sure what else it exports, need something which we can eventually map to a processor/tdp.

> [!note]
> Most importantly this model can returns MULTIPLE observations for every input observation. So you can have one observation as the input which defines the query and they the model returns multiple observations which can then be used in the pipeline, see below.

## Behavior
What does the model do to turn the observations into impacts? List any important equations or references.

Based on the code from @yelghali https://github.com/yelghali/imapct-engine-framework/blob/main/src/lib/components/azure_vm.py a python  model which given an observation with some params, queries Azure and returns multiple observations in a format that can be piped to more models for further calculation.

## Assumptions
What are the core assumptions this model makes?

## Limitations
In what situations is this model limited in it's function, behaviour, accuracy etc...

- Only works with Azure since it works with the Azure SDK.

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
inputs: 
  - timestamp: 2023-07-06T00:00
    duration: 86400 # 1 day
    azure-observation-window: 3600 # 1 min buckets
    azure-observation-aggregation: average
    azure-subscription-id: c60d99da-0c45-4dfa-bc21-87e3c4cb4716
    azure-resource-group: my-application
    azure-vm-name: vm1
    
```

### Output

> [!note]
> It outputs multiple observations in a format that can be used by other models in a pipeline.
> This is the first model in a pipeline which you can use to easily export data for further processing.

```yaml
inputs: 
  - timestamp: 2023-07-06T00:00
    duration: 86400 # 1 day
    azure-observation-window: 3600 # 1 min buckets
    azure-observation-aggregation: average
    azure-subscription-id: c60d99da-0c45-4dfa-bc21-87e3c4cb4716
    azure-resource-group: my-application
    azure-vm-name: vm1
    azure-metrics: cpu
outputs: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cpu-util: 23
    mem-util: 3.2
    cloud-instance-type: c124
    cloud-region: west-us
    cloud-vendor: azure
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cpu-util: 23
    mem-util: 3.2
    cloud-instance-type: c124
    cloud-region: west-us
    cloud-vendor: azure
    ....
```
