### ISSUE TITLE
Model Plugin - co2js

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#156]
- **What**: Create a model to interact with the CO2.js library
- **Why**: So we can use this model for network transfer estimation and other use cases where co2.js is used.
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Has documentation been written for someone writing an IMPL using this model?
- [ ] Has the `units.yml` been updated to take into consideration the params used in this model

## Config
- `model`: swd | 1byte as per the documentation https://developers.thegreenwebfoundation.org/co2js/models/

## Observation
_List the variables this model expects in an input observation_
- `bytes-transmitted`: The number of bytes transmitted over a network
- `green-web-host`: **Optional** Boolean, is the host the data is coming from defined as a green web host according to the green web foundation?

## Impacts
_List the variables this model exports out as an impact_
- `carbon`: Amount of carbon in gCO2e emitted for this network transfer according to the CO2js model.

## Behavior
_What does the model do to turn the observations into impacts? List any important equations or references._

- See: https://developers.thegreenwebfoundation.org/co2js
- We're leveraging CO2.js model to use the network carbon calculations. 
- Converting bytes transmitted to carbon.

## Assumptions
_What are the core assumptions this model makes?_
- There are many assumptions and the methodology is documented here: https://developers.thegreenwebfoundation.org/co2js/explainer/methodologies-for-calculating-website-carbon/

## Limitations
In what situations is this model limited in it's function, behaviour, accuracy etc...
- N/A

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
```yaml
config:
   model: swd
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    bytes-transmitted: 100000
```

### Output

```yaml
config:
   model: swd
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    bytes-transmitted: 100000
impacts: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    bytes-transmitted: 100000
    carbon: 10
```
