### ISSUE TITLE
Model Plugin - time-sync

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#170]
- **What**: A core "built-in" model plugin which synchronizes all the observations in the provided series into a series.
- **Why**: So we can place all the outputs and impacts onto a grid which can then be aggregated up.
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Has documentation been written for someone writing an IMPL using this model?
- [ ] Has the `units.yml` been updated to take into consideration the params used in this model

## Config
- `start-time`: The date-time to start the series.
- `end-time`: The end time to finish the series.
- `duration`: The number of seconds in each interval duration.
- `count`: The number of buckets in the series.
- `weighting`: The algorithm to use to weight the values in buckets, the default is `time` (the only current algorithm is time)

**NOTE**: Both start-time and end time cannot be provided at the same time, it's either one or the other.

## Observation
_List the variables this model expects in an input observation_
- N/A

## Impacts
_List the variables this model exports out as an impact_
- N/A

### Overview

- Every component has a time series of observations but there is no guarantee they match is duration, times, overlap. No guarantee of any form at all.
- This model define a global time series, with a fixed start and end time, consistent set of buckets of the same duration.
- The goal of this model is to snap all the time series for all the components (where this model is configured on the pipeline) to that global time series.

### Global Time Series

If `start-time` has been defined then we create a series which starts at the start time and then moves forward in time. Each bucket `duration` seconds long and there are `count` buckets. We start in the past and move forward in time.

If `end-time` has been defined then we create a time series which **ends** at end time and then create the time series by going backwards in time.

We suspect the most useful use case is to choose an end-time of now and go backwards rather than to choose a start time and go forwards but we provide both.

**NOTE**: A possible v2 feature might be a way for models to scan the whole graph and automatically determine the start-end times from the observations present in the system.

### Normalization

The goal of this model is to snap the observations to this global time series.

>[!note]
> The output observation might be zero for a given time and duration. It means nothing was running then, so there could not be any emissions from the component.

An observation might be of a longer or smaller duration than the new globally defined duration or overlaps the new duration in some way. There can be many algorithms we can use to bucket/slice up the values, but a good default strategy is to use a weighting of time. 

### Example

Take, for example the below, it has mixed durations, some are 5, and some are 15mins.

| Timestamp        | Duration | Energy | Location | Grid | Operational |
| ---------------- | -------- | ------ | -------- | ---- | ----------- |
| 2023-07-06T00:00 | 15       | 43     | west-us  | 500  | 4.7         |
| 2023-07-06T15:00 | 5        | 20     | west-us  | 490  | 2.9         |
| 2023-07-06T20:00 | 5        | 18     | west-us  | 470  | 2.8         |

If we had decided to bucket the outputs in 5 mins increments, we would specify a `duration` of 5 mins. How to normalize the buckets to 5 min durations?

This effectively boils down to a choice of what weighting to use. The simplest would be to weight by time. So the first duration is 15 mins long; if we wanted to visualize in 5 min buckets, we would divide the impacts by 3.

| Timestamp        | Duration | Energy | Location | Grid | Operational |
| ---------------- | -------- | ------ | -------- | ---- | ----------- |
| 2023-07-06T00:00 | 5        | 14.3   | west-us  | 500  | 1.57        |
| 2023-07-06T05:00 | 5        | 14.3   | west-us  | 500  | 1.57        |
| 2023-07-06T10:00 | 5        | 14.3   | west-us  | 500  | 1.57        |
| 2023-07-06T15:00 | 5        | 20     | west-us  | 490  | 2.9         |
| 2023-07-06T25:00 | 5        | 18     | west-us  | 470  | 2.8         |

>[!important]
> The decision to **weight** an observation to the new duration or just copy it is determined by its aggregation param in the units.yaml https://github.com/Green-Software-Foundation/ief/blob/dev/src/config/units.yaml. If the aggregation is "sum" then we would divide it. If the aggregation is avg (or another) then we simply copy it. **This needs further thought and clarification, there may be many other cases that we are not thinking about clearly here.**

## Assumptions
What are the core assumptions this model makes?
- One core assumption is that a time weighting is the right approach.
- Another assumption is that we can decide the weighting using the aggregation param in the units.yaml.

## Limitations
In what situations is this model limited in it's function, behaviour, accuracy etc...

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
config:
  start-time: 2023-07-06T00:00
  duration: 300
  count: 5
  weighting: time
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 900
    location: west-us
    energy: 42.9
    grid-ci: 500
    operational-carbon: 4.71    
  - timestamp: 2023-07-06T15:00
    duration: 300
    location: west-us
    energy: 20
    grid-ci: 490
    operational-carbon: 2.9
  - timestamp: 2023-07-06T25:00
    duration: 300
    location: west-us
    energy: 18
    grid-ci: 470
    operational-carbon: 2.8       
```

### Output

```yaml
config:
  start-time: 2023-07-06T00:00
  duration: 300
  count: 5
  weighting: time
impacts:
  - timestamp: 2023-07-06T00:00
    duration: 300 
    location: west-us
    energy: 14.3
    grid-ci: 500
    operational-carbon: 1.57
  - timestamp: 2023-07-06T05:00
    duration: 300
    location: west-us
    energy: 14.3
    grid-ci: 500
    operational-carbon: 1.57
  - timestamp: 2023-07-06T10:00
    duration: 300
    location: west-us
    energy: 14.3
    grid-ci: 500
    operational-carbon: 1.57    
  - timestamp: 2023-07-06T15:00
    duration: 300
    location: west-us
    energy: 20
    grid-ci: 490
    operational-carbon: 2.9
  - timestamp: 2023-07-06T25:00
    duration: 300
    location: west-us
    energy: 18
    grid-ci: 470
    operational-carbon: 2.8
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 900
    location: west-us
    energy: 42.9
    grid-ci: 500
    operational-carbon: 4.71    
  - timestamp: 2023-07-06T15:00
    duration: 300
    location: west-us
    energy: 20
    grid-ci: 490
    operational-carbon: 2.9
  - timestamp: 2023-07-06T25:00
    duration: 300
    location: west-us
    energy: 18
    grid-ci: 470
    operational-carbon: 2.8    
```
