### ISSUE TITLE
Model Plugin - tdp

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#173]
- **What**: A model plugin that returns the TDP for a given processor
- **Why**: So we can use the tdp value in downstream models
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Has documentation been written for someone writing an IMPL using this model?
- [ ] Has the `units.yml` been updated to take into consideration the params used in this model

## Config
- N/A

## Observation
_List the variables this model expects in an input observation_
- `physical-processor`: The name of the processor (unsure if name is the unique key, or processor codename, or family? needs some investigation)

## Impacts
_List the variables this model exports out as an impact_
- `tdp`: The thermal design power for this CPU

## Behavior
What does the model do to turn the observations into impacts? List any important equations or references.

For a given processor name/family/core returns the TDP. 

There are various sources of TDP, if we can source via an API that would be great, if we need to source manually into a CSV file that works also.

https://en.wikipedia.org/wiki/List_of_CPU_power_dissipation_figures
https://rapidapi.com/ranjian0/api/cpu-data/details
https://www.techpowerup.com/cpu-specs/
https://www.cpubenchmark.net/cpu.php?cpu=AMD+Ryzen+7+7730U&id=5215

## Assumptions
What are the core assumptions this model makes?
- TDP is mapped to a processor name.
- Everyone uses the same processor name to refer to the same processor.

## Limitations
In what situations is this model limited in it's function, behaviour, accuracy etc...
- N/A

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    physical-processor: Intel Core i9-14900K
```

### Output

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    physical-processor: Intel Core i9-14900K
impacts: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    physical-processor: Intel Core i9-14900K
    tdp: 125
```
