### ISSUE TITLE
aggregation feature

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#320]
## Story
As a user I want to be able to aggregate impacts with some configurability so that I can get morte useful indights about how to tune my application. As a developer shipping this feature I need to know what needs to be implemented and how so that I can start building.

## Rationale
The aggregation feature is quite large and complex so we are dedicating a whole sprint to it. The first task is to collate all the information currently available to us, synthesize and critique it so that we have a good conceptual understanding of the requirements. Then we can draft an implementation plan to run past leadership, before building the feature in the second half of the sprint.

## Implementation details
- review video and spec documentation and agree concept
- devise draft implementation plan
- schedule call with Asim to sign off or course correct

## Priority
5

## Scope
No code changes in this specific task - here we will determine how to change the codebase

## Size
3 days

## What does "done" look like?
- an implementation plan for `aggregate` that we can confidently pitch to Asim

## Does this require updates to documentation or other materials??
no

## What testing is required?
None

## Is this a known/expected update?
Discussed in sprint planning 0-4/12/23

**Comment by jmcook1186** [comment]
Our implementation plan:
@narekhovhannisyan 

## Time sync:
- time sync will be a model
- the model is *required* in every pipeline and must be executed before SCI
- the model will take `start`, `end` and `interval` args
- time syncing will happen as follows:
    - convert timestamps to UNIX time so we can aim for continuous, numeric, monotonically increasing x values 
    - for each impact divide by duration to get impact/s
    - replace each observation with `duration` number of timestamps, each with value impact/s
    - iterate over total desired timespan - if unix timestamp exists in inputs, skip, if not insert an entry with impacts set to 0
    - this gives continuous per-second data without gaps
    - sum batches of values according to `interval`
- overwrite inputs with the newly synced input data

## Aggregation
- aggregation should be a framework feature
- aggregation method will be defined in `units.yml`
- throw an error if inputs are not time sync'd
- grouping is all done implicitly based on graph heirarchy
- sum or average synchronous timespans across components within a grouping node

**Comment by jmcook1186** [comment]
Update: horizontal aggregation is shipped, vertical aggregation in progress. Vertical aggregation development got delayed a few days by a bugfix that took priority (the bug was a blocker on properly implementing vertical aggregation anyway)

**Comment by jmcook1186** [comment]
At start of sprint 5 - approx 30-40% done, requires time in sprint 5

**Comment by jawache** [comment]
Hi @jmcook1186 and @narekhovhannisyan,

I wanted to weigh in a little bit on the aggregation issue; I mentioned in today's call that I would share the kind of YAML I would expect to be formed during an aggregation run to ensure we are on the same page. 

I've written out what a graph YAML might look like if we were doing "both" aggregation with just the "carbon" metric.

```yaml
graph:
  outputs: # total per time bucket for the whole graph
    - timestamp: 2023-01-24T11:00
      duration: 360        
      carbon: 19
    - timestamp: 2023-01-24T11:05
      duration: 360        
      carbon: 12
    - timestamp: 2023-01-24T11:10
      duration: 360        
      carbon: 12
  aggregated:
    carbon: 43        
  children:
    application:
      outputs: # aggregated up the tree for every grouping node
        - timestamp: 2023-01-24T11:00
          duration: 360        
          carbon: 19
        - timestamp: 2023-01-24T11:05
          duration: 360        
          carbon: 12
        - timestamp: 2023-01-24T11:10
          duration: 360        
          carbon: 12      
      aggregated:
        carbon: 43          
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6    
          aggregated:
            carbon: 15                            
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1                                                
          aggregated:
            carbon: 16
```

A good way of visualizing what aggregation should be achieved is by looking at a table/CSV-style output.

Key | Aggregated | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | -- | --
graph.carbon | 43 | 19 | 12 | 12
graph.children.application.carbon | 43 | 19 | 12 | 12
graph.children.application.children.vm1.carbon | 12 | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 15 | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 16 | 12 | 3 | 1

## Vertical Aggregation

Talking first about vertical aggregation, what this means is that for each grouping node we have a set of time buckets (which match the time buckets of the component nodes) and the parameters in there are the aggregate of the parameters in the sub-component buckets like so:

**Before:**

```yaml
graph:    
  children:
    application:            
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6                               
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1  
```

If the above graph were exported to CSV we would see this:

Key | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | --
graph.carbon |   |   |  
graph.children.application.carbon |   |   |  
graph.children.application.children.vm1.carbon | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 12 | 3 | 1

Notice that the grouping nodes have no values. Vertical aggregation is about filling in those values.

**After:**

```yaml
graph:
  outputs: # total per time bucket for the whole graph
    - timestamp: 2023-01-24T11:00
      duration: 360        
      carbon: 19
    - timestamp: 2023-01-24T11:05
      duration: 360        
      carbon: 12
    - timestamp: 2023-01-24T11:10
      duration: 360        
      carbon: 12      
  children:
    application:
      outputs: # aggregated up the tree for every grouping node
        - timestamp: 2023-01-24T11:00
          duration: 360        
          carbon: 19
        - timestamp: 2023-01-24T11:05
          duration: 360        
          carbon: 12
        - timestamp: 2023-01-24T11:10
          duration: 360        
          carbon: 12              
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6                               
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1
```

If the above was exported to CSV we would see this:

Key | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | --
graph.carbon | 19 | 12 | 12
graph.children.application.carbon | 19 | 12 | 12
graph.children.application.children.vm1.carbon | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 12 | 3 | 1

Notice how the grouping nodes and the root graph node has values.

Vertical aggregation should aggregate up the tree to the root graph node.

#### Vertical aggregation nodes should just be called `outputs`

It makes sense to just call those nodes outputs since they represent exactly the same thing as the outputs node in the component, just the outputs for that grouping of components.

It also would make the job of every exporter easier; any exporter like the #411 exporter or the #298 would just need to look at any node called `outputs` and not have to figure out if its looking at a grouping node vs component nodes and if it should be looking in `aggregated outputs` vs `outputs`. 

### Horizontal Aggregation

This type of aggregation simply sums up the values for every time series in a component and grouping nodes. If we started with the version of the YAML we ended up with at the end of the vertical aggregation like so:

**Before:**

```yaml
graph:
  outputs: # total per time bucket for the whole graph
    - timestamp: 2023-01-24T11:00
      duration: 360        
      carbon: 19
    - timestamp: 2023-01-24T11:05
      duration: 360        
      carbon: 12
    - timestamp: 2023-01-24T11:10
      duration: 360        
      carbon: 12      
  children:
    application:
      outputs: # aggregated up the tree for every grouping node
        - timestamp: 2023-01-24T11:00
          duration: 360        
          carbon: 19
        - timestamp: 2023-01-24T11:05
          duration: 360        
          carbon: 12
        - timestamp: 2023-01-24T11:10
          duration: 360        
          carbon: 12              
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6                               
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1
```

We would end up with something like so:

**After:**

```yaml
graph:
  outputs: # total per time bucket for the whole graph
    - timestamp: 2023-01-24T11:00
      duration: 360        
      carbon: 19
    - timestamp: 2023-01-24T11:05
      duration: 360        
      carbon: 12
    - timestamp: 2023-01-24T11:10
      duration: 360        
      carbon: 12
  aggregated:
    carbon: 43        
  children:
    application:
      outputs: # aggregated up the tree for every grouping node
        - timestamp: 2023-01-24T11:00
          duration: 360        
          carbon: 19
        - timestamp: 2023-01-24T11:05
          duration: 360        
          carbon: 12
        - timestamp: 2023-01-24T11:10
          duration: 360        
          carbon: 12      
      aggregated:
        carbon: 43          
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6    
          aggregated:
            carbon: 15                            
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1                                                
          aggregated:
            carbon: 16  
```

Which if it was exported to CSV would look like so:

Key | Aggregated | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | -- | --
graph.carbon | 43 | 19 | 12 | 12
graph.children.application.carbon | 43 | 19 | 12 | 12
graph.children.application.children.vm1.carbon | 12 | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 15 | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 16 | 12 | 3 | 1

Horizontal aggregation sums up each time series for each node in the tree, component and grouping nodes.

### Order of operations

Given the above, if you just did horizonal aggregation WITHOUT vertical aggregation then you would end up with something like so:

Key | Aggregated | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | -- | --
graph.carbon |   |   |   |  
graph.children.application.carbon |   |   |   |  
graph.children.application.children.vm1.carbon | 12 | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 15 | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 16 | 12 | 3 | 1

Notice that the component nodes have a single aggregated value, but the grouping nodes do not since we did not first do vertical aggregation. That's totally fine but just a constraint that if you do both, first we need to do vertical and then horizontal to ensure we have the right data.
