### ISSUE TITLE
Model - Mock Observations

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#332]
- **What**: A model plugin which generates fake observation data for testing and debugging
- **Why**: So downstream models can be built which take advantage of data provided in this format, without the respective importers having been built.
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Is the code documented?

#### **User Story**: As a user I can generate a series of observations for a **single machine** running in the cloud that **differ only by cpu-util**

The yaml configuration below will generate 3 observations 
```yaml
timestamp-from: 2023-07-06T00:00 # the start time of the series of observations
timestamp-to: 2023-07-06T10:00 # the start time of the series of observations
duration: 300 # the duration of a single observartion
components:
  - instance-type: A1
generators:
  common:
    region: uk-west
  randint:
    cpu-util:
      min: 1
      max: 99
```
The output represented as a table looks like so:

||2023-07-06 00:00|2023-07-06 00:05|2023-07-06 00:10|
|---|---|---|---|
|instance-type  <br>region  <br>cpu-util|A1  <br>uk-west  <br>99|A1  <br>uk-west  <br>23|A1  <br>uk-west  <br>12|

The output represented as YAML looks like so:

```yaml
outputs:
  - timestamp: 2023-07-06T00:00
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 99
  - timestamp: 2023-07-06T05:00 
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 23	  
  - timestamp: 2023-07-06T10:00
    duration: 300
    instance-type: A1 
    region: uk-west
    cpu-util: 12  	  
```

#### **User Story**: As a user I can generate a series of observations for **two machine running in the cloud** that differ only by cpu-util

This YAML config defines 6 observations
```yaml
timestamp-from: 2023-07-06T00:00 # the start time of the series of observations
timestamp-to: 2023-07-06T10:00 # the start time of the series of observations
duration: 300 # the duration of a single observartion
components:
    - instance-type: A1
    - instance-type: B1
generators:
    common:
        region: uk-west
    randint:
      cpu-util:
        min: 1
        max: 99
```

Represented as a table this looks like so:

||2023-07-06 00:00|2023-07-06 00:05|2023-07-06 00:10|
|---|---|---|---|
|instance-type  <br>region  <br>cpu-util|A1  <br>uk-west  <br>99|A1  <br>uk-west  <br>23|A1  <br>uk-west  <br>12|
|instance-type  <br>region  <br>cpu-util|B1  <br>uk-west  <br>11|B1  <br>uk-west  <br>67|B1  <br>uk-west  <br>1|

Represented as output Yaml this looks like so:
```yaml
outputs:
  - timestamp: 2023-07-06T00:00
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 99
  - timestamp: 2023-07-06T05:00 
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 23	  
  - timestamp: 2023-07-06T10:00
    duration: 300
    instance-type: A1 
    region: uk-west
    cpu-util: 12
  - timestamp: 2023-07-06T00:00 # note this time restarts at the start timstamp
    duration: 300 
    instance-type: B1
    region: uk-west
    cpu-util: 11
  - timestamp: 2023-07-06T05:00 
    duration: 300 
    instance-type: B1
    region: uk-west
    cpu-util: 67
  - timestamp: 2023-07-06T10:00
    duration: 300 
    instance-type: B1
    region: uk-west
    cpu-util: 1  	  
```
	
#### **User Story**: As a user I can generate a series of observations for a **two machines running in the cloud each in different regions** that differ by cpu-util

```yaml
timestamp-from: 2023-07-06T00:00 # the start time of the series of observations
timestamp-to: 2023-07-06T10:00 # the start time of the series of observations
duration: 300 # the duration of a single observartion
components:
  - instance-type: A1
    region: uk-west
  - instance-type: B1
    region: uk-east
generators: 
  randint:
    cpu-util:
      min: 1
      max: 99
```

Represented as a table this looks like so:

||2023-07-06 00:00|2023-07-06 00:05|2023-07-06 00:10|
|---|---|---|---|
|instance-type  <br>region  <br>cpu-util|A1  <br>uk-west  <br>99|A1  <br>uk-west  <br>23|A1  <br>uk-west  <br>12|
|instance-type  <br>region  <br>cpu-util|B1  <br>uk-east  <br>11|B1  <br>uk-east  <br>67|B1  <br>uk-east  <br>1|

Represented as output Yaml this looks like so:
```yaml
outputs:
  - timestamp: 2023-07-06T00:00
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 99
  - timestamp: 2023-07-06T05:00 
    duration: 300 
    instance-type: A1 
    region: uk-west
    cpu-util: 23	  
  - timestamp: 2023-07-06T10:00
    duration: 300
    instance-type: A1 
    region: uk-west
    cpu-util: 12
  - timestamp: 2023-07-06T00:00 # note this time restarts at the start timstamp
    duration: 300 
    instance-type: B1
    region: uk-east
    cpu-util: 11
  - timestamp: 2023-07-06T05:00 
    duration: 300 
    instance-type: B1
    region: uk-east
    cpu-util: 67
  - timestamp: 2023-07-06T10:00
    duration: 300 
    instance-type: B1
    region: uk-east
    cpu-util: 1	  	  
```
### Conceptual Understanding

- We are generating a matrix of data which is represented as a single flat array of observations.
- The x-axis is time, each column is one time-bucket.
- The y-axis is pseudo-components (the model won't actually return fully formed component nodes, it will return a flat array but with the help of the future as yet un-speced grouping model will group these observations into proper components).
- Each cell in our matrix forms one observation
- This is how I imagine most importers will return the data, a flat array of observations for everything being run in the cloud. It's going to be the responsibility of the grouping model to group these observations into proper component/grouping nodes that just contain data for one component.
### Understanding the configuration

Let's break down this one example to help explain:
```yaml
timestamp-from: 2023-07-06T00:00 # the start time of the series of observations
timestamp-to: 2023-07-06T10:00 # the start time of the series of observations
duration: 300 # the duration of a single observartion
components:
    - instance-type: A1
    - instance-type: B1
generators:
    common:
        region: uk-west
    randint:
      cpu-util:
        min: 1
        max: 99
```

The first three rows are going to be used to figure out the number of columns, for example

```yaml
timestamp-from: 2023-07-06T00:00 # the start time of the series of observations
timestamp-to: 2023-07-06T10:00 # the start time of the series of observations
duration: 300 # the duration of a single observartion
```
By looking at the from and to timestamps and duration we know there will be 3 time-buckets, 2023-07-06T00:00, 2023-07-06T05:00 and 2023-07-06T00:10, these will form the columns in our matrix.

The next thing to do is to figure out the rows, for this we look at the components part of the config:
```yaml
components:
    - instance-type: A1
    - instance-type: B1
```
This means for each of the 3 time buckets we will have effectively two rows of data that contain the parameters defined above.

Which will end up looking something like so if we were to visualize it as a table:

|   |   |   |   |
|---|---|---|---|
||2023-07-06 00:00|2023-07-06 00:05|2023-07-06 00:10|
|instance-type|A1|A1|A1|
|instance-type|B1|B1|B1|

So far this is static data, we need some dynamic "fake" data to output for each of these component cells and that's where the generator config section comes into play

```yaml
generators:
    common:
      region: uk-west
      cloud: azure
    randint:
      cpu-util:
        min: 1
        max: 99
      mem-util:
        min: 1
        max: 99        
```

A generator returns a set of parameters which are appended to the existing parameters in each cell in our matrix, they are added to the observation we are creating in each cell in our matrix.

In the above example there are two generator *types*, `common` and `randint`, each returns two parameters, `common` returns `region` and `cloud` and `randint` returns `cpu-util` and `mem-util`. 

- `common` just returns the data underneath it and saves us repeating the data in the components section above if it's always the same.
- `randint`, for each param inside creates a random int between the values in min and max.

**NOTE**: Generators need to know the historical data in the timeseries for the component they are working on. This will future-proof generators that will be created to simulate say cpu-utilization that gradually increases and decreases instead of each bucket having a random value. To simulate something like that the generator will need to know the past data.

Generators are classes which implement this interface
```typescript
class Generator:
	function initialise(name: string, config: object): void
	function next(historical: array): object
```
So based on the above example there will be 4 instances of generators made.

```ts
generators = [
	new Common("region", "uk-west"),
	new Common("cloud", "azure"),
	new RandInt("cpu-util", {"min": 1, "max: 99"}),
	new RandInt("mem-util", {"min": 1, "max: 99"})
]
```
For each cell in the matrix we loop through the generator list calling `next` and append the returned parameters to the cell (to the observation we are creating)

### Algorithm

**NOTE**: I talked about about generating a matrix, that's just to comprehend what's going on but the algorithm itself will just loop through and generate observations and append to a flat list.

The overall pseudo algorithm should be something like so:
- initialize all the generators
- from the config figure out the number of time-buckets, the columns of our matrix.
- from the config figure out the rows in the matrix from the number of components.
- for each component
	- for each time-bucket
		- create an empty observation object
		- copy the component information into that empty observation object
		- call next on every generator, take the output and add that that to our observation object
		- append the observation object to our list of output observations.

I believe if we do that approach we will generate a list of outputs as the user stories above and have a way of generating a wide variety of data with minimal config from the user side.

### References

https://github.com/faker-js/faker
https://github.com/jakubnowicki/fixtuRes
