### ISSUE TITLE
Model Plugin - GroupBy

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#385]
- **What**: A model plugin groups observations from one component into a group of sub-components
- **Why**: So we can restructure flat observations into more useful groupings for later analysis

# User Stories

### Assumptions
A major assumption is that observations will be typically provided in a **flat structure**. By flat, we mean a single **array of observations with duplicate entries for the same time period**.

Take, for example, the case of a cloud application with 3 virtual machines in use all the time; when we import data, each of the VMs will be running at the same time, so we will have multiple observations for the same time bucket. 

The goal of the **GroupBy** function is to take this flat single-dimensional array of observations and return a grouping of components. Ultimately, the grouping can be however the user decides, but for the Time Synchronisation to work, the components need to end up with no duplicate entries for times.

### Positional Recommendations
- This should be performed before time-synchronization to ensure that each component has a time series without duplicates.
- In fact, a common approach might be a pipeline like so
	- some-importer-that-returns-a-flat-array-of-observaations
	- grouping
	- time-synchronisation
	- all
	- the
	- other
	- models
### Example

Let's take, for example, this manifest file. The inputs are a flat series of observations with multiple observations for each time bucket.

This is how the observations might be returned from an Importer or the MockImporter, a single flat array.

Currently, importers can only return a flat array of observations since the function signature only supports that return.

```yaml
name: if-demo
description: demo pipeline
graph:
  children:
    my-app:
      pipeline:     
        - group-by
        - teads-curve
      config:
        group-by:
          - cloud-region
          - instance-type
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 300 
          instance-type: A1 
          region: uk-west
          cpu-util: 99
        - timestamp: 2023-07-06T05:00 
          duration: 300 
          instance-type: A1 
          region: uk-west
          cpu-util: 23	  
        - timestamp: 2023-07-06T10:00
          duration: 300
          instance-type: A1 
          region: uk-west
          cpu-util: 12
        - timestamp: 2023-07-06T00:00 # note this time restarts at the start timstamp
          duration: 300 
          instance-type: B1
          region: uk-west
          cpu-util: 11
        - timestamp: 2023-07-06T05:00 
          duration: 300 
          instance-type: B1
          region: uk-west
          cpu-util: 67
        - timestamp: 2023-07-06T10:00
          duration: 300 
          instance-type: B1
          region: uk-west
          cpu-util: 1	       
```

Two things to note in the above yaml:

1. The observations for one component are for two instances in different regions.
2. We, therefore, have duplicate entries at the same time.

We have some configurations above,

```yaml
    my-app:
      pipeline:     
        - group-by
        - teads-curve
```

The above means we are going to run the grouping node before the teads-curve model

```yaml
      config:
        group-by:
          - cloud-region
          - instance-type
```

The above config means that the grouping node will group the observations first by instance type and then by cloud region, so the output will look like so:

```yaml
graph:
  children:
    my-app:
      pipeline:
        # - group-by
        - teads-curve
      config:
        group-by:
          groups:
            - cloud-region
            - instance-type
      children:
        uk-west:
          children:
            A1:
              inputs:
                - timestamp: 2023-07-06T00:00
                  duration: 300
                  instance-type: A1
                  region: uk-west
                  cpu-util: 99
                - timestamp: 2023-07-06T05:00
                  duration: 300
                  instance-type: A1
                  region: uk-west
                  cpu-util: 23
                - timestamp: 2023-07-06T10:00
                  duration: 300
                  instance-type: A1
                  region: uk-west
                  cpu-util: 12
        uk-east:
          children:
            B1:
              inputs:
                - timestamp: 2023-07-06T00:00
                  duration: 300
                  instance-type: B1
                  region: uk-east
                  cpu-util: 11
                - timestamp: 2023-07-06T05:00
                  duration: 300
                  instance-type: B1
                  region: uk-east
                  cpu-util: 67
                - timestamp: 2023-07-06T10:00
                  duration: 300
                  instance-type: B1
                  region: uk-east
                  cpu-util: 1                    
```

A few very important things to note.

- This used to be a component node (no children, just inputs) and it's now turned into a grouping node (no inputs, just children)
- In the output file we've commented out the grouping function in the pipeline.
- If we kept the grouping function in the pipeline and we tried to run this file again, then it will try to group something that's already grouped, as a min that would be a waste of time and at worst it might create some other issues.
- I thought it might be best to keep it in there and just comment it out or just give some hint that some grouping was performed since that's important information for the manifest file.
- We need to discuss this approach and the idea of whether an output manifest file should always be executable again, idempotent - how do we want to think of that conceptually?

The output above added a **children** node, and underneath, there are some components grouped using the criteria defined in the grouping config.

Each component now has a time series of observations **without any duplicates**, and we have a hierarchy in the tree that would be useful when aggregating up, e.g., the user might want to see the emissions by instance type/VM and then also the aggregate emissions by region. 

With user-defined grouping, the end user can take any flat observation array and generate any grouping they want based on the data available. 

## As a user, I can write a model plugin that returns a set of nested components instead of just a flat array of observations

This type of model plugin requires a different function signature since it needs to return a grouping of components.

Rather than overload the same function name I think it would be best to introduce a new function signature called group

```ts
interface ModelPluginInterface {
  public configure(name: string, config: Configuration): ModelPluginInterface
  public execute(inputs: Arrray<ModelParam>): Array<ModelParam>
  public group(inputs: Arrray<ModelParam>): Object???
}
```

The return signature of the group is TBD and requires discussion.

## As a user, I can configure a model plugin that calls the new group interface instead of execute

When configuring plugins that perform this type of activity, perhaps there can be an additional parameter to the model's config called `function`. By default, if not defined, it calls the `execute` function and expects this model to return just a flat array of observations.

But if you specify it explicitly as the group, it will execute the `group` function instead and expect a nested set of components as a response and act accordingly.

```yaml
initialize:
  models:
    - name: group-by
      model: Grouping
      path: built-in
      function: group
```
