### ISSUE TITLE
CSV Exporting Functionality

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#411]
## Story
As a user, I want to export the entire graph as a CSV to analyze the data in other applications.

## Rationale
Trying to navigate and understand the impacts of your software application by looking at YAML is very challenging. By exporting into a flat table structure of a CSV, a human can better understand how the impacts are broken down by component and time.

## Implementation details

This is an extension to IF that outputs the tree in a CSV format.

ie --manifest <in> --exhaust csv --filter comma,seperated,list,of,parameters,to,export

The manifest is in the format of a YAML that has been processed by impact engine like so

```yaml

graph:
  outputs: # total per time bucket for the whole graph
    - timestamp: 2023-01-24T11:00
      duration: 360        
      carbon: 19
    - timestamp: 2023-01-24T11:05
      duration: 360        
      carbon: 12
    - timestamp: 2023-01-24T11:10
      duration: 360        
      carbon: 12
  aggregated:
    carbon: 43        
  children:
    application:
      outputs: # aggregated up the tree for every grouping node
        - timestamp: 2023-01-24T11:00
          duration: 360        
          carbon: 19
        - timestamp: 2023-01-24T11:05
          duration: 360        
          carbon: 12
        - timestamp: 2023-01-24T11:10
          duration: 360        
          carbon: 12      
      aggregated:
        carbon: 43          
      children:
        vm1:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 5                  
          aggregated:
            carbon: 12
        vm2:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 4
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 5
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 6    
          aggregated:
            carbon: 15                            
        vm3:
          outputs: 
            - timestamp: 2023-01-24T11:00
              duration: 360        
              carbon: 12
            - timestamp: 2023-01-24T11:05
              duration: 360        
              carbon: 3
            - timestamp: 2023-01-24T11:10
              duration: 360        
              carbon: 1                                                
          aggregated:
            carbon: 16                                        
```

The output CSV file should be of this format:

Path | Aggregated | 2024-01-25:11-00 | 2024-01-25:11-05 | 2024-01-25:11-10
-- | -- | -- | -- | --
graph.carbon | 43 | 19 | 12 | 12
graph.children.application.carbon | 43 | 19 | 12 | 12
graph.children.application.children.vm1.carbon | 12 | 3 | 4 | 5
graph.children.application.children.vm2.carbon | 15 | 4 | 5 | 6
graph.children.application.children.vm3.carbon | 16 | 12 | 3 | 1

### How to choose the path?

The path column should be a javascript-like path, which we can use to easily identify the node in the graph this parameter relates to.

**NOTE**: it might be redundant to have `children` so many times in the key; we may consider stripping that out for brevity and ease of reading.

### To aggregate or not?

If aggregated data is present, it should be added to the first column called aggregated. 

### What if the data is not time-synchronized?

We have a problem! If aggregated data is present then maybe just print out that column, but probably just error out since the columns won't make sense.

## Priority
4/5 this tool would be very useful to debug and test other features in IF including aggregating.

## Scope
This is an external tool to IF, so other than some docs, it won't affect other things too much.

## Size
Several days perhaps including testing.

## What does "done" look like?
- A script that exports a variety of different graphs
- Documentation regarding what types of graph structures it works with and where it will error out.

## Does this require updates to documentation or other materials??
It will need documentation.

## What testing is required?
Yes, a variety of different graph types.

## Is this a known/expected update?
Related to this
https://github.com/Green-Software-Foundation/if/issues/298
