### ISSUE TITLE
Model Plugin - Sum

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#443]
- **What**: A plugin called sum which does summation on inputs
- **Why**: So we can perform logical operations in a pipeline
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Is the code documented?

## Global Config
N/A

```yaml
initialize:
  plugins:
    sci-e:
      config:
        input-parameters:
          - cpu/energy
          - mem/energy
          - network/energy
        output-parameter: energy
      path: built-in
      model: SumModel
    sum-all-energy:
      config:
        input-parameters:
          - cpu/energy
          - mem/energy
          - network/energy
        output-parameter: energy
      path: built-in
      model: SumModel
    sum-some-energy:
      config:
        input-parameters:
          - cpu/energy
          - mem/energy
        output-parameter: energy
      path: built-in
      model: SumModel
    sum-all-carbon:
      config:
        input-parameters:
          - operational-carbon
          - embodied-carbon
        output-parameter: carbon
      path: built-in
      model: SumModel
```

## Node Config
- `input-parameters`: array list of all input params you want to sum up.
- `output-parameter`: a string of the name of the output parameter you want to output to.

## Inputs
_List the variables this model expects in an input input_
- `variable`: Description

## Outputs
_List the variables this model exports out as an impact_
- `variable`: Description

## Behavior

- Add a constant to an input and publish that to the output.
- Add multiple inputs together and publish that to an output.
- If there is no input parameter, default to 0

## Assumptions
- All units are respected. This will not be doing any normalization.

## Limitations
- Only does summation within an observation, not summation across observations.

## Example
Provide at least one example of some input config and inputs. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the input.

### Input

```yaml
config:
 key: value
inputs: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
```

### Output

```yaml
pipeline:
  - sci-e
inputs: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    yyyy: zzzz
outputs: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    yyyy: zzzz
    aaaa: bbbb
```
