### ISSUE TITLE
[if-unofficial-models]: watttime invalid geolocation causes unknown error

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#480]
**Describe the bug**
Wattime plugin causes unknown error when executed with invalid geolocation.

**To Reproduce**
1. Setup valid watttime manifest.
2. Use `7.7749,-122.4194` as a geolocation.
3. Run the if framework.

**Expected behavior**
Handle invalid value gracefully.

**Actual behavior**
Throws unknown error for the if framework, which addresses user to report an issue.

**Screenshots**
![Screenshot 2024-02-29 at 12 42 25 AM](https://github.com/Green-Software-Foundation/if/assets/109615222/7251ae54-7859-4830-ad03-38316e4236c6)

**Additional context**
Manifest:
```yaml
name: watt-time
description: simple demo invoking watt-time
tags:
initialize:
  plugins:
    watt-time:
      method: WattTimeGridEmissions
      path: '@grnsft/if-unofficial-models'
      global-config:
        username: ENV_WATT_TIME_USERNAME
        password: ENV_WATT_TIME_PASSWORD
tree:
  children:
    child:
      pipeline:
        - watt-time
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 3600
          geolocation: 7.7749,-122.4194
```
