### ISSUE TITLE
Create divide model

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#481]
## Story
As a developer I want to be able to divide a parameter by a number so I can use that parameter in downstream plugins.

## Rationale

`boavizta-cpu` need `cpu/number-cores` to work, however cloud-metadata returns `vcpus-allocated`, to get number of cores you divide vcpus-allocated by 2.

## Implementation details

- Create a plugin called divide, following the same method as Sum and Multiply.
- Divides a parameter by a specific configured number
- Output the number to a configured output parameter

```yaml
config
  divide:
    numerator: the name of the parameter we are going to divide
    denominator: IF STRING(the name of the parameter we are going to divide) IF NUMBER(the number we will divide by)
    output: the name of the parameter we will output to.
```

For example, divide one input by another input

```yaml
config
  divide:
    numerator: vcpus-allocated
    denominator: duration
    output:  vcpus-allocated-per-second
```

For example, divide one input by a number

```yaml
config
  divide:
    numerator: vcpus-allocated
    denominator: 2
    output:  cpu/number-cores
```

## Priority
5/5 - Required for workshop

## Scope

Not affecting anything else.

## Size
1 day

## What does "done" look like?
Divide plugin which divides two numbers as above.

## Does this require updaes to documentation or other materials??
Yes, documentation to if-models for this plugin

## What testing is required?
Unit tests and manual invocation from a manifest file

## Is this a known/expected update?
For sprint 7, added after sprint planning.
