### ISSUE TITLE
WattTime returning incorrect values for grid/carbon-intensity

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#504]
**Describe the bug**

- Changing the number of observations changes the `grid/carbon-intensity` returned from the WattTime plugin.
- Each observation also has exactly the same (incorrect) `grid/carbon-intensity` added to the outputs, to 10 dp. For a duration of a few hours the grid carbon intensity for a region should change, maybe not by much but even a few dp's should be as an absolute minimum be expected, but really over a few hours we should expect significant changes.

**To Reproduce**
1. Run this manifest file.

```
name: basic-demo
description: null
tags: null
initialize:
  outputs: ['yaml']
  plugins:
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions           
tree:
  children:
    application:
      pipeline:
        - watttime
      defaults:  
        geolocation: 37.7749,-122.4194  
      inputs:
        - timestamp: '2024-02-26 00:00:00'
          duration: 3600
        - timestamp: '2024-02-26 01:00:00'
          duration: 3600
        - timestamp: '2024-02-26 02:00:00'
          duration: 3600
        - timestamp: '2024-02-26 03:00:00'
          duration: 3600        
        - timestamp: '2024-02-26 04:00:00'
          duration: 3600             
        - timestamp: '2024-02-26 05:00:00'
          duration: 3600  
        - timestamp: '2024-02-26 06:00:00'
          duration: 3600                      
```

3. Add/remove observations and re-run.

**Expected behavior**
- The `grid/carbon-intensity` for the observation should be the average of the values returned from WattTime for that geolocation, timestamp and duration. WattTime might return multiple carbon intensity for that duration and we use the average of all of them.
- Different timestamps should return different grid/carbon intensity.

**Screenshots**
- Video of the bug: https://drive.google.com/file/d/1Mou5tyB6xQ4rzAEsD6rQgmhNcdtAj7p7/view?usp=sharing

**Additional context**
