### ISSUE TITLE
Grouping nodes computing a pipeline after group-by has converted it from a component node into a grouping node

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#506]
**Describe the bug**

- When you use group-by in a pipeline and there are plugins **after** the group-by, it still carries on running subsequent plugins on the current node (which after a group-by should be treated as a grouping node only and therefore have no inputs and no outputs unless they have been aggregated up).
- The result is extra output nodes on the new grouping node in the tree which is confusing but also more seriously means we double count impacts.
- This is all using the current latest npm released version of @grnsft/if @grnsft/if-plugins

**To Reproduce**

Run this manifest file.

```yaml
name: My Manifest File
description: My First Manifest File 💚
initialize:
  outputs: ['yaml']
  plugins: 
    # teads-curve:
    #   path: '@grnsft/if-unofficial-plugins'
    #   method: TeadsCurve
    #   global-config:
    #     interpolation: spline
    cloud-metadata:
      method: CloudInstanceMetadata
      path: "@grnsft/if-plugins"    
    # operational-carbon:
    #   path: '@grnsft/if-plugins'
    #   method: Multiply
    #   global-config:
    #     input-parameters: ['cpu/energy', 'grid/carbon-intensity']
    #     output-parameter: 'carbon'       
    # watttime:
    #   path: '@grnsft/if-unofficial-plugins'           
    #   method: WattTimeGridEmissions      
    mock-observations:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: 2024-03-05T00:00
        timestamp-to: 2024-03-05T00:00
        duration: 360
        components:
          - name: server-1 
            cloud/instance-type: Standard_A1_v2
          # - name: server-2
          #   cloud/instance-type: Standard_E64_v3
        generators:
          common:
            cloud/region: uk-west
            cloud/vendor: azure
          randint:
            cpu/utilization:
              min: 1
              max: 99
    group-by: 
      path: 'builtin'
      method: GroupBy              
tree: 
  pipeline:
    - mock-observations
    - group-by
    - cloud-metadata
  config:
    group-by:
      group: 
        - cloud/vendor      
        - cloud/region
        - name
  inputs: null
```

The output looks like so:

```yaml
name: My Manifest File
description: My First Manifest File 💚
tags: {}
initialize:
  plugins:
    cloud-metadata:
      path: '@grnsft/if-plugins'
      method: CloudInstanceMetadata
    mock-observations:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: 2024-03-05T00:00
        timestamp-to: 2024-03-05T00:00
        duration: 360
        components:
          - name: server-1
            cloud/instance-type: Standard_A1_v2
        generators:
          common:
            cloud/region: uk-west
            cloud/vendor: azure
          randint:
            cpu/utilization:
              min: 1
              max: 99
    group-by:
      path: builtin
      method: GroupBy
  outputs:
    - yaml
tree:
  pipeline:
    - mock-observations
    - group-by
    - cloud-metadata
  config:
    group-by:
      group:
        - cloud/vendor
        - cloud/region
        - name
  children:
    azure:
      children:
        uk-west:
          children:
            server-1:
              inputs:
                - timestamp: '2024-03-05 00:00:00'
                  duration: 360
                  name: server-1
                  cloud/instance-type: Standard_A1_v2
                  cloud/region: uk-west
                  cloud/vendor: azure
                  cpu/utilization: 26
              outputs:
                - timestamp: '2024-03-05 00:00:00'
                  duration: 360
                  name: server-1
                  cloud/instance-type: Standard_A1_v2
                  cloud/region: uk-west
                  cloud/vendor: azure
                  cpu/utilization: 26
                  vcpus-allocated: 1
                  vcpus-total: 52
                  memory-available: 2
                  physical-processor: >-
                    Intel® Xeon® Platinum 8272CL,Intel® Xeon® 8171M 2.1
                    GHz,Intel® Xeon® E5-2673 v4 2.3 GHz,Intel® Xeon® E5-2673 v3
                    2.4 GHz
                  cpu/thermal-design-power: 205
  outputs:
    - timestamp: '2024-03-05 00:00:00'
      duration: 360
      name: server-1
      cloud/instance-type: Standard_A1_v2
      cloud/region: uk-west
      cloud/vendor: azure
      cpu/utilization: 26
      vcpus-allocated: 1
      vcpus-total: 52
      memory-available: 2
      physical-processor: >-
        Intel® Xeon® Platinum 8272CL,Intel® Xeon® 8171M 2.1 GHz,Intel® Xeon®
        E5-2673 v4 2.3 GHz,Intel® Xeon® E5-2673 v3 2.4 GHz
      cpu/thermal-design-power: 205
```

**Expected behavior**

The output should look like this (**NOTE**: The extra outputs node on the tree should not be there):

```yaml
name: My Manifest File
description: My First Manifest File 💚
tags: {}
initialize:
  plugins:
    cloud-metadata:
      path: '@grnsft/if-plugins'
      method: CloudInstanceMetadata
    mock-observations:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: 2024-03-05T00:00
        timestamp-to: 2024-03-05T00:00
        duration: 360
        components:
          - name: server-1
            cloud/instance-type: Standard_A1_v2
        generators:
          common:
            cloud/region: uk-west
            cloud/vendor: azure
          randint:
            cpu/utilization:
              min: 1
              max: 99
    group-by:
      path: builtin
      method: GroupBy
  outputs:
    - yaml
tree:
  pipeline:
    - mock-observations
    - group-by
    - cloud-metadata
  config:
    group-by:
      group:
        - cloud/vendor
        - cloud/region
        - name
  children:
    azure:
      children:
        uk-west:
          children:
            server-1:
              inputs:
                - timestamp: '2024-03-05 00:00:00'
                  duration: 360
                  name: server-1
                  cloud/instance-type: Standard_A1_v2
                  cloud/region: uk-west
                  cloud/vendor: azure
                  cpu/utilization: 26
              outputs:
                - timestamp: '2024-03-05 00:00:00'
                  duration: 360
                  name: server-1
                  cloud/instance-type: Standard_A1_v2
                  cloud/region: uk-west
                  cloud/vendor: azure
                  cpu/utilization: 26
                  vcpus-allocated: 1
                  vcpus-total: 52
                  memory-available: 2
                  physical-processor: >-
                    Intel® Xeon® Platinum 8272CL,Intel® Xeon® 8171M 2.1
                    GHz,Intel® Xeon® E5-2673 v4 2.3 GHz,Intel® Xeon® E5-2673 v3
                    2.4 GHz
                  cpu/thermal-design-power: 205
```

**Screenshots**
N/A

**Additional context**

- When you use group-by in a pipeline, it converts the current component node into a grouping node.
- This means that any plugins after the group-by should only be applied to the new child component nodes and the current node should stop executing any more plugins in the pipeline, since grouping nodes don't have inputs any more.
- See the pseudo code in the compute proposal in the refactor doc for the logic: https://hackmd.io/8pXKEzEGRB6gJjtVzFCqRQ?view#computecontext-tree-plugins

```ts    
    // Go through the plugins top to bottom
    while (pipeline) {
      // Pops the first item from pipeline
      pluginName = pipeline.shift()
      plugin = plugins[pluginName]
      // We need some meta data about the plugin so we know what function to call.
      if (plugin.meta.kind === "execute") {
        // This is a normal execute plugin, will return outputs
        inputs = plugin.execute(config.plugin, inputs)
        // `inputs` now equals the outputs of the last plugin
      }
      else if (plugin.meta.kind === "groupby") {
        // This is a groupby plugin, it will return child components NOT outputs
        node.children = plugin.execute(config.plugin, inputs);
        for (let child in node.children) {
          // `pipeline` now equals the remaining plugins to apply to each child
          computeNode(child, pipeline, defaults, config);
        }
        // get out of the while loop, we don't want to process any more plugins we are a grouping node now
        break;
      }
    }
```

If during computation the current node is a component node and the plugin is a groupby plugin
- compute the current node
- compute the children
- break <- this stops the grouping node from executing the other plugins and exits the loop.
