### ISSUE TITLE
E-mem and E-net plugins don't have checking for global config

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#567]
**Describe the bug**
E-mem and E-net plugins don't have fallback values for `energy-per-gb` . So in cases when `energy-per-gb` is null or empty, 

**To Reproduce**
1. Run the followig manifest
```yaml
name: sci-e-demo
description:
tags:
initialize:
  plugins:
    e-net:
      method: ENet
      path: "@grnsft/if-plugins"
      # global-config:
      #   energy-per-gb: 
tree:
  children:
    child:
      pipeline:
        - e-net
      config:
        e-net:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          network/data-in: 1
          network/data-out: 2
```
**Expected behavior**
should be checked if global config exists, then check the inside values .

Actual result:
error:     Cannot read properties of undefined (reading 'energy-per-gb')
