### ISSUE TITLE
[Watt-time] Signal type is ignored when geolocation is in inputs

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#583]
Run watt-time manifest , where inputs contain geolocation and signal type.
**_Actual result:_** Api request fails, because provided signal type is ignored.
**_Expected:_** To check if inputs contain signal type, then if yes, include it into the request, else fetch signal type.

```
name: cloud-instance-metadata
description: example impl invoking Cloud Instance Metadata plugin
tags:
initialize:
  # outputs: ["yaml", "csv"]
  plugins:
    watttime:
      path: "@grnsft/if-unofficial-plugins"
      method: WattTimeGridEmissions
    cloud-instance-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        # - cloud-instance-metadata
        - watttime
      config:
        cloud-instance-metadata:
          fields:
             - cloud/region-wt-id
            # - cloud/region-geolocation
      inputs:
        - timestamp: "2024-03-05T00:00:00.000Z" # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 100
          # cloud/vendor: azure
          # cloud/region: westeurope
          cloud/instance-type: Standard_E64_v3
          cpu/utilization: 10
          # geolocation: 36.7783,-119.417931
          cloud/region-wt-id: CAISO_NORTH
          signal-type: co2_moer
```
