### ISSUE TITLE
[Watt-time] Error when cloud/region value is not provided

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#585]
Run the following manifest, which doesn't contain cloud/region value.

**Actual result:** Error  fetching data from Wattime Api.
**Expected result:** Should fetch the region from Wattime APi, which corresponds to the provided geolocation.

```
name: cloud-instance-metadata
description: example impl invoking Cloud Instance Metadata plugin
tags:
initialize:
  # outputs: ["yaml", "csv"]
  plugins:
    watttime:
      path: "@grnsft/if-unofficial-plugins"
      method: WattTimeGridEmissions
    cloud-instance-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        # - cloud-instance-metadata
        - watttime
      config:
        cloud-instance-metadata:
          fields:
             - cloud/region-wt-id
            # - cloud/region-geolocation
      inputs:
        - timestamp: "2024-03-05T00:03:00.000Z" # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 100
          cloud/vendor: azure
          # cloud/region: westeurope
          cloud/instance-type: Standard_E64_v3
          cpu/utilization: 10
          geolocation: 37.7749,-122.4194
          # geolocation: 52.0055,37.9587
          # cloud/region-wt-id: FR
          signal-type: co2_moer
```

![Image](https://github.com/Green-Software-Foundation/if/assets/109615222/bcc6d655-4ae3-4af3-8d30-5c7dc0313004)
