### ISSUE TITLE
👍🏼 Update IF to report runtime information to outputs

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#591]
**Sub of**: #629  -> #650 

**Why**

As a user I want to capture everything needed to audit and verify the results from my IF run. Currently, the IF outputs do not include information about the machine the code is run on, versions, environment details etc. 

**Context**
Providing granular runtime details in the output file will help to audit and verify IF outputs.

**SoW**
- [x] Implement the feature in IF source code
- [x] Test and QA
- [x] Documentation is updated to describe new info in outputs 

**Prerequisites**

None

**Acceptance Criteria**
- [x] Output manifest file records all the information required to understand and replicate the environment it was run in.

**GIVEN** the user is in a folder
**WHEN** they compute the manifest file
**THEN** the output manifest file has these nodes
- `execution`
  - `command`: The exact command line used to run
  - `environment`: Information about the runtime environment
    - `os`: Name of OS
    - `os-version`: Version of OS
    - `node version`: Version of Node
    - `date-time`: Datetime of the run including timezone.
    - `dependancies`: The dependancies gathered from running `npm list`
      - `<package-name>` : `<package-version>`
      - `@grnsft/if-plugins`: `@v0.3.2 (git+ssh://git@github.com/Green-Software-Foundation/if-plugins.git#8056a9593e3d41786d32dddb3e080bba75a8aa54)`
      - `@grnsft/if-unofficial-plugins`: `0.3.1`

 - [x] Documentation is updated to describe new info in outputs.

**Example Manifest**
There are no changes required to the manifest format, but when it is executed additional information should be added to the output file. We can use the following manifest as an example (this is basic.yml from IF repo):

```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20

```

The output file should look as follows:

```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
execution:
  command: ie --manifest examples/basic.yml
  environment:
    os: ubuntu
    os-version: 22.04.6
    node version: v21.4.0
    date-time: 2023-12-12T00:00:00.000Z (UTC)
    dependencies: 
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
          cpu/thermal-design-power: 100
          cpu/energy: 0.000013270071138211382
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
          cpu/thermal-design-power: 100
          cpu/energy: 0.000025568089430894314
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20
          cpu/thermal-design-power: 100
          cpu/energy: 0.000013270071138211382
```
