### ISSUE TITLE
Design a generic `interpolation` plugin

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#622]
Sub of: #656

**what**

Create a generic interpolation plugin destined to live in `if/plugins`. 

**why**

We prefer to maintain generic plugins to do arithmetic operations rather than plugins that are hardcoded with parameter values for specific use cases. Specific use cases are then served by combining arithmetic plugins, passing in appropriate values. This makes things much more flexible, configurable and maintainable. This specific plugin is intended to support the deprecation and removal of our `teads-curve` plugin. Instead of having a plugin just for that specific curve, we can provide a generic `interpolation` plugin and pass in the known `x` and `y` values representing the curve. 

Note that to fully replicate the `teads-curve` plugin the `interpolate` plugin will have to be part of a pipeline with `multiply` and `divide` plugins too.

**Acceptance criteria**

- [ ] The plugin should support linear, spline and polynomial interpolation methods.
- Linear interpolation is a method of estimating values that fall between known values. It involves determining the value at a point on a straight line between two known points of curve fitting using linear polynomials to construct new data points within the range of a discrete set of known data points.

 - Polynomial - Polynomial interpolation involves fitting a polynomial function to a set of data points. We intend to use Lagrange's interpolation. Higher-order polynomials can capture more complex relationships but have over-fitting risks.

 - Spline - Spline interpolation uses piecewise-defined polynomial functions (usually low-degree) to interpolate between data points. A spline consists of multiple polynomial segments, often cubic, that are smoothly connected at specific points. Splines provide a balance between flexibility and smoothness, making them suitable for approximating functions with complex variations.

- [ ] The plugin should accept the following global config:
- `method` - Specifies the interpolation method for the data. Acceptable values are 'linear', 'spline', or 'polynomial'. The default method is linear. (optional) 
- `x` - Array of points. Numbers should be in ascending order (required). (In the old version the points are hardcoded: [0, 10, 50, 100]. Could it be optional to support the same hard-coded values?) (can it be in node-config ?)
- `y` - Array of numbers. Numbers should be in ascending order (required) 
- `input-parameter` - a string defining the name to use its value to calculate the interpolation. It should match an existing key in the `inputs` array.
- `output-parameter` - a string defining the name to use to add the result of interpolation with additional calculation

- [ ] the plugin should validate that the lengths of `x` and `y` are equal

- [ ] The plugin should accept the following data from `inputs`:
- `timestamp` -  a timestamp for the input  (required)
- `duration` - the amount of time, in seconds, that the input covers.  (required)
- `input-parameter` - a field whose name matches the string provided to `input-parameter` in global config (i.e. if the `input-parameter` in global config is `cpu/utilisation` then `cpu-utilisation` must exist in the input data)

- [ ] The plugin outputs a value `z` that is the result of looking up the `y` value at `x` = `input-parameter` using the user-defined interpolation method. `z` is assigned to a field with a name defined by `output-parameter` in the output data.

- [ ] Unit tests have been added to the builtin repository
- the unit tests accompanying the feature code should have 100% coverage.

- [ ] Documentation has been added in the form of a feature README and linked out from `if.greensoftware.foundation`

**Example Manifest**

```yaml
name: interpolation-demo
description: simple demo of interpolation plugin
tags:
initialize:
 plugins:
   interpolation:
     method: Interpolation
     path: "builtin"
     global-config:
       method: linear
       x: [0, 10, 50, 100]
       y: [0.12, 0.32, 0.75, 1.02]
       input-parameter: “cpu/utilization”
       output-parameter: “interpolation-result”
tree:
 children:
   child:
     pipeline:
       - interpolation
     inputs:
       - timestamp: 2023-07-06T00:00
         duration: 3600
         cpu/utilization: 10
```

Executing this manifest should yield the following result:

```yaml
name: interpolation-demo
description: simple demo of interpolation plugin
tags:
initialize:
 plugins:
   interpolation:
     method: Interpolation
     path: "builtin"
     global-config:
       method: linear
       x: [0, 10, 50, 100]
       y: [0.12, 0.32, 0.75, 1.02]
       input-parameter: “cpu/utilization”
       output-parameter: “interpolation-result”
tree:
 children:
   child:
     pipeline:
       - interpolation
     inputs:
       - timestamp: 2023-07-06T00:00
         duration: 3600
         cpu/utilization: 10
    outputs:
       - timestamp: 2023-07-06T00:00
         duration: 3600
         cpu/utilization: 10
         interpolation-result: 0.12
```

**Note on teads curve**

The interpolation described in the example above gives the `y` value from the Tead's curve for any given `x` value. We pass in `cpu/utilisation` as an `x` value and receive the appropriate `y`. The `y` value is a scaling factor that should be multiplied by the `cpu/thermal-design-power` to yield `cpu/energy`. You may also want to scale the result by the ratio of allocated and total vcpus. Doing *all* these steps together replicate the existing `teads-curve` plugin, but only the interpolation part is in scope for this plugin.
