### ISSUE TITLE
Build `if-env`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#636]
**Sub of**: #629  -> #650 

**What**: A CLI tool that helps you setup your local environment to run a manifest file.

**Why**: As a user I want to be able to quickly create an environment to run my manifests, taking all my plugins into account.

**Context**: We can provide a command line tool that will inspect the package.jsons of the if and all the plugins listed in a manifest and create a unified package.json that can be used to define the environment in which the manifest can run. This will make it easy for users to run manifests and will also be useful scaffolding for our sandboxes, playgrounds and scenario testing. This ticket covers the design and specification but not the actual building of the tool.

**DoD**
- [x] Feature merged into `if` main branch
- [x] Feature documented on if.greensoftware.foundation

**SoW**
- [x] TODO

**Pre-requisites**
- #591 

**Acceptance Criteria**

- [x] Running `if-env` to setup a blank starter environment

**GIVEN** the user is in a folder
**WHEN** they run `if-env` with no parameters
**THEN** it generates a `package.json` file in the local directory which contains everything they need to start writing a manifest file with.
**AND** it generates a template manifest file called `manifest.yml` with a selection of fields prepopulated to help with development.

Here is a proposal for a template `manifest.yml` to create _if_ `if-env` is executed from a folder with no local yaml files:

```yaml
name: template manifest # rename me!
description: auto-generated template # update description!
tags: # add any tags that will help you to track your manifests
initialize:
  outputs:
    - yaml # you can add - csv to export to csv
  plugins: # add more plugins for your use-case
    memory-energy-from-memory-util: # you can name this any way you like!
      method: Coefficient # the name of the function exported from the plugin
      path: '@grnsft/if-plugins' # the import path
      global-config: # anmy config required by the plugin
        input-parameter: ['memory/utilization']
        coefficient: 0.0001 #kwH/GB
        output-parameter: 'memory/energy'
tree:
  children: # add a chile for each distinct component you want to measure
    child:
      pipeline: # the pipeline is an ordered list of plugins you want to execute
        - memory-energy-from-memory-util # must match the name in initialize!
      config: # any plugin specific, node-level config
      inputs:
        - timestamp: 2023-12-12T00:00:00.000Z # ISO 8061 string
          duration: 3600 # units of seconds
          memory/utilization: 10 
```

- [x] Running `if-env` to setup an environment to run a given manifest file

**GIVEN** the user has this manifest file

```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
execution:
  command: ie --manifest examples/basic.yml
  environment:
    os: ubuntu
    os-version: 22.04.6
    node version: v21.4.0
    date-time: 2023-12-12T00:00:00.000Z (UTC)
    dependencies: 
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.2 (git+ssh://git@github.com/Green-Software-Foundation/if-plugins.git#8056a9593e3d41786d32dddb3e080bba75a8aa54)
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
```

**AND** they are in a folder which doesn't contain a package.json
**WHEN** they run `if-env /path/to/<manifest>.yml`
**THEN** it generates a `package.json` file in the local directory which contains all the script and dependencies required to run the manifest file.

- [x] Running `if-env` to create and install an environment to run a given manifest file

**GIVEN** the user has this manifest file
```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
execution:
  command: ie --manifest examples/basic.yml
  environment:
    os: ubuntu
    os-version: 22.04.6
    node version: v21.4.0
    date-time: 2023-12-12T00:00:00.000Z (UTC)
    dependencies: 
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.2 (git+ssh://git@github.com/Green-Software-Foundation/if-plugins.git#8056a9593e3d41786d32dddb3e080bba75a8aa54)
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
```
**AND** they are in a folder which doesn't contain a package.json
**WHEN** they run `if-env /path/to/manifest.yml --install`
**THEN** it generates a `package.json` file in the local directory which contains all the script and dependencies required to run the manifest file
**AND** it runs `npm install` to install the dependencies.

**Comment by narekhovhannisyan** [comment]
@jawache The Github project is registered in package.json's dependencies. 

1. package.json contains something like this when a Github dependency is installed:
```json
dependencies: {
"yourpackage": "https://github.com/yourpackage" // repository name is registered as a package
}
```

2. Manifest can include either Github repository link or package name (both can do). But as you said we don't have guarantee that user will put it rather than repo name.

**Comment by jawache** [comment]
Thanks @narekhovhannisyan, I think we have enough now to refine this properly.

When you install from GitHub you call this command.

`npm install https://github.com/Green-Software-Foundation/if-plugins` 

This adds this record to package.json

```
{
  "name": "copy-plugin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@grnsft/if-plugins": "github:Green-Software-Foundation/if-plugins"
  }
}
```
And when you run `npm list` you get this result

```
copy-plugin@1.0.0 /Users/jawache/Development/gsf/copy-plugin
└── @grnsft/if-plugins@v0.3.2 (git+ssh://git@github.com/Green-Software-Foundation/if-plugins.git#8056a9593e3d41786d32dddb3e080bba75a8aa54)
```

But when you configure the plugin in the manifest file you lose the link to github and version info.

Since we only contain information like so

```
    operational-carbon:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']
        output-parameter: 'carbon'     
```

Similarly when we install from npm directly like so

`npm install @grnsft/if-unofficial-plugins`

The package.json looks like this:

```
{
  "name": "copy-plugin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@grnsft/if-plugins": "github:Green-Software-Foundation/if-plugins",
    "@grnsft/if-unofficial-plugins": "^0.3.1"
  }
}
```

And npm list returns

```
➜  copy-plugin npm list                                 
copy-plugin@1.0.0 /Users/jawache/Development/gsf/copy-plugin
├── @grnsft/if-plugins@v0.3.2 (git+ssh://git@github.com/Green-Software-Foundation/if-plugins.git#8056a9593e3d41786d32dddb3e080bba75a8aa54)
└── @grnsft/if-unofficial-plugins@0.3.1
```

So if-env needs to know the exact package names, versions and sources so it can compute the same packge.json as the manifest file was originally run in.

I'll update #591 with the relevant information but to summarize when computing a manifest file we should include the output from `npm list` in the execution node so that if-env has enough information to be able to generate a package.json that can run this manifest file.
