### ISSUE TITLE
Build `if-diff` core feature

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#637]
**Sub of**: #629  -> #650 

**What**

A command line utility that compares two manifest files and returns both a code and useful console logs for showing where two manifest files differ.

**Why**

As a user who needs to compare manifests files I would find it very useful to have a command line tool that can rapidly report whether two manifests are identical and if not how they differ.

**Context**

We can create a convenience tool for users to quickly see how manifests differ. This tool needs to be designed and specified before we start building. This ticket covers designing and documenting the tool prior to building.
The tool should be able to categorize differences, something along the lines of 'identical', tree match, context-match no-overlap or similar. The user should be able to get granular detail about where and how the manifests differ, similar to git diff.

**CLI details**:

- `if-diff` is a script separate from `ie` - it is self contained and can be included in `if/package.json`.
- `if-diff` should take two arguments: `--source` and `--target`
  - `source` is the "test case" file that represents the source of truth 
  - `target` is the file that is being compared against `source`
- `if-diff` should only be able to return either `FILES MATCH` or the details of the *first* difference it encounters. 
- `if-diff` should be able to receive a `source` from stdin as well as from a file path passed on the command line, e.g. `ie --manifest source.yml | if-diff --target target.yml`
- `if-diff` should emit an exit value: 
  - `0`: files match
  - `1`: files did not match
  - `2`: some other error occurred during execution

**Matching rules**
- all file content should be included in the matching
- `if-diff` should support wildcard characters (`*`) that allow any value to count as a match
  - e.g. if `source` includes `cpu-util: *` then both `cpu-util: 45` and `cpu-util: 55` in the same position in `target` should be accepted as a match. Pass on *any* value - no need to check types etc here at the moment.

**Output display format**

- If `if-diff` finds no in-scope differences between the `source` and `target` then it should return a success flag: `FILES MATCH` and exit code `0`.
- If `if-diff` detects an in-scope difference between the files, it should halt execution, return exit code `1` and report the error to the command line. The report should include the yaml path to the differing element in the tree, the value in the `source` and the value in the `target`, using the following schema:
```
Files do not match!
<yaml path to non-matching element>
source: <value in source file>
target: <value in target file>
```

If the difference relates to a missing node in the tree for `source` or `target` then `<value in x file`> should be either `exists` or `missing` and the yaml path should point to the highest level element that is missing (e.g. if an entire child component is missing, provide the path to the child component).

e.g. difference values detected: 
```
Files do not match!
tree.children.vm1[4].cpu/utilization
source: 45
target:  43
```

**Prerequisites**
- #615

**Related Issues:**
- [ ] #706
- [ ] #707
 
**SoW**
- [ ] Implement acceptance criteria
- [ ] `if-diff` outputs conform to the schema defined in the `rationale` section above
- [ ] Unit tests includes positive and negative test cases in `if` reposiroty
- [ ] unit tests have 100% coverage and passing
- [ ] Create PR
- [ ] Incorporate PR feedback

**Acceptance Criteria**

### Scenario 1: Executing `if-diff`
- [ ] `if-diff` exists as a standalone tool that comes bundled with `if`
	- it is included in `if/package.json`
	- it is invoked using the `if-diff` command 
	- it takes two arguments: `--source`and `--target`
	- it returns EITHER; the string `FILES MATCH` AND exit code `0` OR a difference report describing the *first* error it encounters while comparing the two files AND exit code `1`.

### Scenario 2: No change detected
- GIVEN the user has downloaded and installed `if`
WHEN they execute `if-diff --source manifest1.yml --target manifest2.yml`
AND both `manifest1.yml` and `manifest2.yml` contain:

```yaml
name: test
description:
tags:
initialize:
  plugins:
    sum:
      method: Sum
      path: "@grnsft/if-plugins"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy"
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
          energy: 0.002
```

THEN: `if-diff` should return `FILES MATCH` and exit code `0`.

### Scenario 3: Change detected
GIVEN the user has downloaded and installed `if`
WHEN they execute `if-diff --source manifest1.yml --target manifest2.yml`
AND `manifest-1.yml` contains

```yaml
name: test
description:
tags:
initialize:
  plugins:
    sum:
      method: Sum
      path: "@grnsft/if-plugins"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy"
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
          energy: 0.002

```

but manifest-2.yml contains (different value for `energy/network`):

```yaml
name: test
description:
tags:
initialize:
  plugins:
    sum:
      method: Sum
      path: "@grnsft/if-plugins"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy"
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.002
          energy: 0.003

```

THEN `if-diff` should emit exit code `1` and return
```
Files do not match!
tree.children.child.outputs[0]['network/energy']
source: 0.001
target: 0.002
```

### Scenario 4: Reading output
- [ ] `if-diff` can receive `--source` data from stdin as well as a given filepath
  - this will enable pipes, for example `ie --manifest example1.yml | if-diff --target example-target.yml`

GIVEN a user has downloaded and installed `if`
WHEN they run `if-diff --source manifest-1.yml --target manifest-2.yml` 
WITH `manifest-1.yml` containing:

```yaml
name: test
description:
tags:
execution:
  command: >-
    /home/joe/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/joe/Code/if/src/index.ts --manifest
    /home/joe/Code/if/examples/manifests/basic.yml --stdout
  environment:
    os: linux
    os-version: 5.15.0-102-generic
    node-version: 21.4.0
    date-time: '2024-05-01T08:35:57.060Z'
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-models@v0.1.6-beta'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
initialize:
  plugins:
    sum:
      method: Sum
      path: "@grnsft/if-plugins"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy"
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.002
          energy: 0.003

```

AND `manifest-2.yml` contains

```yaml
name: test
description:
tags:
execution:
  command: >-
    /home/joe/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/joe/Code/if/src/index.ts --manifest
    /home/joe/Code/if/examples/manifests/basic.yml --stdout
  environment:
    os: macOS
    os-version: darwin
    node-version: 21.3.0
    date-time: '2024-05-01T08:45:57.050Z'
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-models@v0.1.6-beta'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
initialize:
  plugins:
    sum:
      method: Sum
      path: "@grnsft/if-plugins"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy"
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.002
          energy: 0.003

```

THEN `if-diff` should emit exit code `0` and return `FILES MATCH`.

- [ ] `if-diff` conforms to the matching rules described above in `rationale` section
e.g. for two manifests whose value in the posiiton `tree.children.vm1.inputs[3]['cpu/energy']`:

```yaml
Files do not match!
tree.children.vm1.inputs[3]['cpu/energy']
source: 45
target:  43
```

for two manifests that have different nodes in their trees:

```yaml
Files do not match!
tree.children.vm1
source: exists
target:  missing
```

- [ ] `if-diff` can accept data from `stdin` instead of a file on disk
- GIVEN a user has downloaded and installed `if`
WHEN they pipe the output from `ie` to `if-diff`, for example using the following command:
`ie --manifest example1.yml --stdout| if-diff --target example-target.yml` 

THEN: they receive an `if-diff` output.
