### ISSUE TITLE
Build `if-check`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#638]
**Sub of**: [#629](https://github.com/Green-Software-Foundation/if/issues/629) -> [#650](https://github.com/Green-Software-Foundation/if/issues/650)

**What**

Build a command line tool called `if-check` that wraps calls to `if-env` and `if-diff`. On the command line, a user can call `if-check`, passing an output file, and the tool will install the necessary dependencies as defined by `if-env` and then `if-diff` the provided output file against a newly generated version obtained by executing the `context` and `tree` sections from the given output file as if it were a fresh manifest.

**Why**

As a user I want to be able to re-execute a manifest and verify that the outputs are correctly reported. `if-check` is a convenience tool that wraps the individual steps required to verify a manifest into a single command.

_The point of this is to verify that a given output file was correctly reported_

Say someone gives you a manifest file to demonstrate the environmental impact of their application. Maybe you don't trust them completely, or are suspicious they've made a mistake. You can just pass their manifest to `if-check` and it will run it back through IF and report whether the given data is accurate or not - if not, `if-check` will report where there are differences.

In terms of the implementation, `if-check` should do the following under the hood:

- run `if-env` on the given manifest (which we can refer to as `manifest.yml` which will recreate the original runtime environment reported in the manifest locally
- run the manifest and save the output to a temporary file (here we can refer to it as `re-executed.yml`)
- run `if-diff` with `if-diff --source manifest --target re-executed.yml`
- report the output from `if-diff` to the console

This means the `if-check` CLI tool can be an alias to:

```
if-env && ie given-file.yml --stdout | if-diff --target given-file.yml
```

The result should be an `if-diff` output, for example:

```
Files match!
```

or 

```
Files do not match!
tree.children.child.inputs[0]['cpu/energy']
source: 50
target: 30
```

- Operating over a folder of manifests

`if-check` should accept a path to a folder of manifests. In this case, it should sequentially operate on every yaml file in the folder. For each yaml file, it should run 

`if-env --install && ie -m <given-file> --stdout | if-diff -t <given-file>`.

It should skip any file that does not have a `.yml` or `.yaml` file extension. If any file causes an unexpected error, it should report the error and then continue to the next file in the folder, until there are no files left to process. 

`if-check` should also log the filename during its execution.

For a folder containing 5 valid manifests:

Provide path to folder to `if-check`

```
if-check --m <path-to-dir>
```

The expected output is:

```sh
file1.yml
Files match! 

file2.yml
Files match! 

file3.yml
Files match! 

file4.yml
Files match! 

file5.yml
Files match! 
```

If any of the files fail the `if-check` validation, the output would look as follows:

```sh
file1.yml
Files match! 

file2.yml
Files match! 

file3.yml
File do not match!
tree.children.child.intputs[0]['energy']
source: 0.002
target: 0.0005

file4.yml
Files match! 

file5.yml
Files match! 
```

The overall aim for this is that we can integrate `if-check` into our CI/CD so that `if-check` can be run over all our demo manifests including success and failure cases and this can be used as the testing suite that gates PRs to `if/main`.

**Acceptance Criteria**

-  A command line tool, `if-check` exists that takes an output file as input, and returns the output from `if-diff`
    
    - The command line tool `if-check` should take a single argument, `--file` whose value should be a path to an output file.
    - IThe `if-env` tool can be run on the output file, given information in it's `execution` block. The output file can then be used as an input to `ie`, to re-run the given it in precisely the same environment (at least at the level of `package.json`, not necessarily at the Node or OS level).
    - The given output file and the file generated by rerunning the manifest should be compared. The `if-check` command should yield precisely the same output as running `if-env` and `if-diff` separately on a file.

- GIVEN a user has downloaded and installed `if`  
    WHEN they run `if-check` passing a valid output file  
    THEN they receive the `if-diff` output comparing their given output file with a new one generated by re-executing the given one

  e.g. the following output file (`example-file.yml`) is provided:
  
```yaml

name: sum
description: successful path
tags: null
initialize:
  plugins:
    sum:
      path: '@grnsft/if-plugins'
      method: Sum
      global-config:
        input-parameters:
          - cpu/energy
          - network/energy
        output-parameter: energy
  outputs:
    - yaml
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/index.ts -m manifests/outputs/test.yaml -o
    manifests/outputs/test2.yml
  environment:
    if-version: v0.3.2
    os: linux
    os-version: 5.15.0-105-generic
    node-version: 21.4.0
    date-time: 2024-05-15T10:28:36.414Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum: null
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
          energy: 0.002

```

The following command is executed:

```
if-check example-file.yml
```

The following response is expected:

```
Files match!
```

The following output file has a deliberate error introduced in the `outputs/energy` field. 

```yaml

name: sum
description: successful path
tags: null
initialize:
  plugins:
    sum:
      path: '@grnsft/if-plugins'
      method: Sum
      global-config:
        input-parameters:
          - cpu/energy
          - network/energy
        output-parameter: energy
  outputs:
    - yaml
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/index.ts -m manifests/outputs/test.yaml -o
    manifests/outputs/test2.yml
  environment:
    if-version: v0.3.2
    os: linux
    os-version: 5.15.0-105-generic
    node-version: 21.4.0
    date-time: 2024-05-15T10:28:36.414Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-plugins@v0.3.2'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
tree:
  children:
    child:
      pipeline:
        - sum
      config:
        sum: null
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          network/energy: 0.001
          energy: 0.0005
```

Running `if-check example-file-2.yml` should yield:

```
File do not match!
tree.children.child.intputs[0]['energy']
source: 0.002
target: 0.0005
```

    
-  A set of identical and non-identical manifests exist as a test set, whose `if-check` outcome we know a priori and can be used to verify that `if-check` is operating correctly.  
    - This might be satisfied naturally as part of [Build `if-diff` core feature #637](https://github.com/Green-Software-Foundation/if/issues/637)
    
- GIVEN the test set exists  
    WHEN a user runs `if-check` on those test manifests  
    THEN the `if-check` output matches the expected outputs
    
-  Documentation exists in the form of a README in the IF repository and a section on `if.greensoftware.foundation/docs/reference/cli`
    
- GIVEN the documentation has been added to if-greensoftware.foundation  
    WHEN a user visits the site and searches for `if-check`  
    THEN they will find a dedicated page explaining the tool, with usage examples.
    

- [x] `if-check` operates on a folder of manifests when a path to a directory is passed in place of a path to a manifest file

  GIVEN the feature is deployed
  WHEN I run `if-check -m /home/user/manifests/`
  THEN `if-check` executes each yaml file in `/home/user/manifests` in turn, reporting the outcome to the console before exiting.

e.g. an example output could look as follows:

```sh
file1.yml
Files match! 

file2.yml
Files match! 

file3.yml
File do not match!
tree.children.child.intputs[0]['energy']
source: 0.002
target: 0.0005

file4.yml
Files match! 

file5.yml
Files match! 
```

- [ ] when `if-check` is passed a path to a folder of manifests handles unexpected errors in manifests without panicking

  GIVEN `if-check` exists
  WHEN I run `if-check -m /home/user/manifests/` and one of the files contains an unexpected error that causes `if-diff` to fail
  THEN `if-check` reports the error to the console and then continues to execute the next file in the folder

e.g. 

```sh
file1.yml
Files match! 

file2.yml
Files match! 

file3.yml
CliInputError:  Provided manifest is not in yaml format.

file4.yml
Files match! 

file5.yml
Files match! 
```

**Prerequisites**

- [👍🏼 Set up CI/CD to trigger automated tests for PRs #621](https://github.com/Green-Software-Foundation/if/issues/621)
- [Document the QA requirements for merging into main/release branches #632](https://github.com/Green-Software-Foundation/if/issues/632)
- [Build `if-env` #636](https://github.com/Green-Software-Foundation/if/issues/636)
- [Build `if-diff` core feature #637](https://github.com/Green-Software-Foundation/if/issues/637)
