### ISSUE TITLE
Shell plugin outputs are double indented and timestamp is not first element

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#694]
## Description of the Error
Running the `shell` plugin with the default `sampler` demo Python script in the `if` repository returns incorrectly formatted output data. Specifically, the outputs are double-indented and in the wrong order.

## Expected Behaviour
After downloading and installing `if` and `if-plugins` and running `npm run ie -- --manifest manifests/plugins/shell/success.yml --output manifests/outputs/test` should yield an output yaml that looks as follows:

```yaml
name: shell
description: successful path
tags: null
initialize:
  plugins:
    shell:
      path: '@grnsft/if-plugins'
      method: Shell
      global-config:
        command: python3 /usr/local/bin/sampler
  outputs:
    - yaml
if-version: v0.3.2
tree:
  children:
    child:
      pipeline:
        - shell
      inputs:
        - timestamp: '2023-11-02T10:35:31.820Z'
          duration: 3600
          cpu/energy: 0.002
          memory/energy: 0.000005
      outputs:
        - timestamp: '2023-11-02T10:35:31.820Z'
          duration: 3600
          cpu/energy: 0.002
          energy: 1
          memory/energy: 0.000005  
```

Notice that the output array has one additional field: `energy: 1`. The other fields are identical to what is found in `inputs`.

## Actual Behaviour
After downloading and installing `if` and `if-plugins` and running `npm run ie -- --manifest manifests/plugins/shell/success.yml --output manifests/outputs/test` yields an output yaml that looks as follows:

```yaml
name: shell
description: successful path
tags: null
initialize:
  plugins:
    shell:
      path: '@grnsft/if-plugins'
      method: Shell
      global-config:
        command: python3 /usr/local/bin/sampler
  outputs:
    - yaml
if-version: v0.3.2
tree:
  children:
    child:
      pipeline:
        - shell
      inputs:
        - timestamp: '2023-11-02T10:35:31.820Z'
          duration: 3600
          cpu/energy: 0.002
          memory/energy: 0.000005
      outputs:
        - - cpu/energy: 0.002
            duration: 3600
            energy: 1
            memory/energy: 0.000005
            timestamp: '2023-11-02T10:35:31.820Z'

```

Notice the double indented first element of `outputs` and the reordering of the `output` data that moves `timestamp` and `duration` out of indexes 0 and 1. `timestamp` should always be the zeroth element in each block of `output` data.

## Steps to Reproduce
Download and install `if`:

```
git clone https://github.com/Green-Software-Foundation/if.git
npm i && npm i @grnsft/if-plugins
```

Run using the bundled example manifest `manifests/plugins/shell/success.yml`

```
npm run ie -- --manifest manifests/plugins/shell/success.yml -- output manifests/output/test
```

Examine contents of `manifests/output/test.yml`

## Link to online environment
I am not providing an online environment because it was awkward to configure a remote IDE to spawn a shell and execute python code. I'll provide manifest details instead.

## Manifest File That Generated the Error

```yaml
name: shell
description: successful path
tags: null
initialize:
  plugins:
    shell:
      path: '@grnsft/if-plugins'
      method: Shell
      global-config:
        command: python3 /usr/local/bin/sampler
  outputs:
    - yaml
if-version: v0.3.2
tree:
  children:
    child:
      pipeline:
        - shell
      inputs:
        - timestamp: '2023-11-02T10:35:31.820Z'
          duration: 3600
          cpu/energy: 0.002
          memory/energy: 0.000005
```

## Runtime Info

Linux
Ubuntu 20.04.5 LTS
Node 21.4.0
