### ISSUE TITLE
Simplify SCI model code to use a single parameter for `functional-unit`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#705]
**What**
Simplify the SCI model code so that it accepts a single parameter representing `functional-unit` instead of two (`functional-unit` and `functional-unit-time` that can be *either* an arbitrary string that matches the name of some numeric value present in the `inputs` *or* a time unit composed of a number and a unit (e.g. `1 minute`, `2 months` etc).

**Why**

SCI is a core feature that has to be as easy as possible to build into pipelines. The current implementation puts some unnecessary burden on the user that could be abstracted away.

**Context**

When we first built the SCI plugin we wanted to be able to normalize carbon values to any functional unit, including functional units that are just units of time. We also wanted to be able to support composites of some functional unit *and* time such as `requests/month`. We ended up supporting this by using two distinct parameters: `functional-unit` and `functional-unit-time`.

Instead, we can just use `functional-unit`, which should come from node-level config. The value of `functional-unit-time` should be a string.

The plugin code should check whether the value of `functional-unit` matches a predefined set of time units (`s`, `sec`, `secs`, `seconds`, `m`, `min`, `mins`, `minutes`....). If the functional unit *is* one of these known time units then applying the `functional-unit` is just a time conversion (incoming `carbon` is always gCO2eq/s).

If the `functional-unit` is one of the known time units with a prepended number, e.g. `5 mins` then the leading number should be used as a multiplier - i.e.

`functional-unit`: `5 mins`
```
carbon per 5 mins = (carbon per second / 60) * 5
```

If `functional-unit` doesn't match either of those patterns, then it should be assumed to be a string that precisely matches the name of some value found in `inputs`, in which case the value associated with that parameter should be used as a scaling factor.

In summary, we already implement all of this logic in our existing plugin, but split across two parameters. We want to wrap it all uyp into one single parameter.

**Prerequisites/resources**
The `sci` plugin should be migrated into `builtins` (see #704 )

**SoW (scope of work)**

- [ ] update source code to use a single parameter
- [ ] documentation updated
- [ ] test cases added

**Acceptance criteria**

- [ ] the SCI plugin accepts a single parameter representing the functional unit, called `functional-unit`
  - the parameter should be a string
  - the plugin should check to see whether the value of `functional-unit` matches a "time" pattern, meaning it includes an optional leading number and a time unit from a predefined list (our current `sci/config.ts` file is fine for this). If so, then perform a simple time conversion. If the value of `functional-unit` does *not* match a time pattern then the plugin should check that the value of `functional-unit` is also a value that appears in `inputs`. 

  - GIVEN the changes have been merged
  WHEN the following manifest is executed (providing a time based functional unit without leading value) :

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: min
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60

```
THEN the following output should be generated (providing sci in units of carbon per minute in each timestep):

```yaml
```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: 1 min
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
          sci: 1
```

  - GIVEN the changes have been merged
  WHEN the following manifest is executed (providing a time based functional unit with leading value) :

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: min
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60

```
THEN the following output should be generated (providing sci in carbon per 5 minutes in each timestep):

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: 5 min
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
          sci: 5
```

  - GIVEN the changes have been merged
  WHEN the following manifest is executed (providing a non-time based functional unit) :

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: requests
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
          requests: 100

```
THEN the following output should be generated (providing carbon per request in each timestep):

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: 1 min
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
          requests: 100
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          energy: 5
          carbon: 60
          sci: 0.6
```

  - GIVEN the changes have been merged
  WHEN the following manifest is executed (defining a `functional-unit` that is missing in `inputs`) :

```yaml
name: sci
description: successful path
tags:
initialize:
  outputs: ['yaml']
  plugins:
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - sci
      config:
        sci:
          functional-unit-time: requests
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 3600
          energy: 5
          carbon: 60

```
THEN Impact Framework should error out.

- [ ] the README documentation is updated 
- [ ] unit tests are updated and have 100% coverage and 100% passing
