### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by DimaRadionov** [Green-Software-Foundation/if#739]
I wanted to run a manifest file and received an error: Cannot convert undefined or null to object. 
## Description of the Error

I was developing a tool, which will track the co2 emmisions. When it all cames to run the manifest file, I received an error. 
## Expected Behaviour

Should run, cause I copied a simple manifest file 
## Actual Behaviour

error:     Cannot convert undefined or null to object
## Manifest File That Generated the Error

name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20
## Runtime Info

[2024-05-27 09:05:51.402 AM] error:     Cannot convert undefined or null to object
TypeError:      Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at listDependencies (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\environment.js:42:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async injectEnvironment (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\environment.js:49:26)
    at async impactEngine (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\index.js:22:25)

**Comment by jmcook1186** [comment]
Hi - sorry but I can't reproduce your error. You pasted the yaml flat, so I can't check whether the indentation was correct. This is how I ran your yaml data in my local IF and it executed fine.

```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20

```
