### ISSUE TITLE
Make `—stdout` the default export option

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#781]
**Why**: Sub of #760 

**What**: Make `--stdout` the default export option if no output option is configured via the CLI

**Context**

The current method for configuring outputs is quite awkward for users. We would like to move to having `--stdout` as the default option, so that when no output configuration is provided on the CLI IF falls back to printing output data to the console.
There may be cases where we want to suppress the output from IF entirely,so we can add a `--no-output` command that blocks IF from reporting output data to the console, but still reports logs and errors.

**Scope of work:**
- [x] Remove `--stdout` command and make reporting output data to the console the default behaviour
- [x] Add a `--no-output` command that prevents IF from outputting its results
- [x] Update CLI documentation and any examples across if-docs

### Scenario 1:
- [x] `--stdout` command is no longer available
  GIVEN the command is removed
  WHEN I run `ie -m <manifest> --stdout`
  THEN I see an error message similar to `stdout command is not known to IF`

### Scenario 2:
- [x] default behaviour for IF is to report results to stdout
  GIVEN the default behaviour is updated
  WHEN I run `ie -m <manifest>`
  THEN I see the computed manifest data in the console.

e.g. the following manifest (note there is no `output` field in `initialize`)

```yaml
name: basic
description: a minimal manifest executing a single plugin on a single component for a single timestep
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: ['yaml']
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20

```

and I run 

```sh
ie -m basic.yml
```

I get the following result in the console:

```
> @grnsft/if@0.3.3-beta.0 ie
> npx ts-node src/index.ts -m manifests/examples/basic.yml --stdout

[2024-06-06 09:47:10.097 AM] info: 
Incubation Project

This project is an incubation project being run inside the Green Software Foundation; as such, we DON’T recommend using it in any critical use case. 

Incubation projects are experimental, offer no support guarantee, have minimal governance and process, and may be retired at any moment. This project may one day graduate, in which case this disclaimer will be removed.

# start
name: basic
description: >-
  a minimal manifest executing a single plugin on a single component for a
  single timestep
tags: null
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/index.ts -m manifests/examples/basic.yml --stdout
  environment:
    if-version: 0.3.3-beta.0
    os: linux
    os-version: 5.15.0-107-generic
    node-version: 21.4.0
    date-time: 2024-06-06T08:47:11.098Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
  status: success
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
          cpu/thermal-design-power: 100
          cpu/energy: 0.000013270071138211382

# end
```

### Scenario 3:
- [x] the `--nos-output` command prevents results being displayed in the console
  GIVEN the command is added
  WHEN I run `ie -m <manifest> --no-output`
  THEN I do not see any results in the console, no file is saved, but I do still see logs and errors in the console.
