### ISSUE TITLE
Make IF export yaml by default

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#782]
**Why**: Sub of #760 
**What**: 
We first assert that IF outputs yaml data only. This can be to a file or to the console. No additional code is required to configure this. Either the IF receives `--output` to trigger saving to a yaml file, or it receives no output config, in which case it prints its data to the console (handled in #781).

This means we can remove the in-manifest config that specifies the output type (`output: - ['yaml']`).

Providing a savepath should be all that’s required to trigger saving to yaml `ie -m <manifest> -o <savepath> `. 

IF should also be able to tell whether a correct file extension was provided in the file extension and correct it if necessary. If the user provides any of `result.yml`, `result.yaml`, `result` or some garbled extension `result.blah` it should always actually save `result.yaml`.

**Scope of work:**

- [x] Implement exhaust logic to remove ability to output to csv using plugins. Receiving a valid path to `--output` triggers aving to yaml file. No output config means print to console (already covered in #781)

- [x] Remove output config from all example manifests 

- [x] implement validation logic that autocorrects the file extension in the savepath provided to `--output` to `.yaml`.

- [x] csv-export and csv-export-raw plugins are removed from the IF repository

### Scenario 1:
- [x] providing savepath is all that is needed to cause IF to save yaml data to file
GIVEN the exhaust logic is updated
WHEN I run `ie -m example.yml -o result.yml`
AND `example.yml` contains the following:

```yaml
name: basic
description: a minimal manifest executing a single plugin on a single component for a single timestep
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30

```

THEN `result,ym` is created and it contains the following:
```yaml
name: basic
description: >-
  a minimal manifest executing a single plugin on a single component for a
  single timestep
tags: null
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs:
    - csv
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/index.ts -m manifests/examples/basic.yml --stdout
  environment:
    if-version: 0.3.3-beta.0
    os: linux
    os-version: 5.15.0-107-generic
    node-version: 21.4.0
    date-time: 2024-06-06T09:37:27.049Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-unofficial-plugins@v0.3.1'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
  status: success
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
          cpu/thermal-design-power: 100
          cpu/energy: 0.000013270071138211382
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30
          cpu/thermal-design-power: 100
          cpu/energy: 0.00001650338753387534
```

- [x] `output` config is removed from all example manifests
- [x] docs explanations and examples are all updated (correct descriptions and no output config in examples)
- [x] providing savepaths with or without `.yml` file extensions both result in saved files with a valid `.yml` extension (i.e. not `.yml.yml` or `.yaml.yml` or anything similar.
