### ISSUE TITLE
Create `if-csv` script

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#784]
**Why**: Sub of #760 

**What**: Refactor `csv-export` feature from plugins to scripts

Instead of being a plugin that operates during the IF execution, `csv-export` can become a separate script that operates on the IF output yaml data. We can refer to this script as `if-csv`.

`if-csv` can be invoked on the command line, taking an IF output file as an argument. Instead of having to create a fiddly command using a hashtag to define the parameter to export as we do today, the script can just expose its own commands to do the same thing more intuitively, for example:

`if-csv --file <example.yml> --params carbon --output output.csv`

The above example will export the carbon parameter from the output data in `example.yml` and save it to `output.csv`.

This can be used to run the exhaust script over an `ie` output without having to re-execute `ie`.

However, in situations where we do want to re-execute `ie`, we can simply pipe `ie` into the `if-csv` script in a single command:

`ie -m <manifest> | if-csv --fields carbon --output output.csv`

We intend for `if-csv` to be bundled into IF, but users can develop their own exhaust scripts with any arbitrary logic and use it in the same way. We'll provide some boilerplate code and a tutorial to help, in a separate ticket.

**Scope of work:**
- [x] Add `if-csv` script to IF
- [x] Add documentation to CLI docs

### Scenario 1:
- [x] `if-csv` is available, exposing the `file`, `params` and `output` commands  
  GIVEN `if-csv` exists
  WHEN I run `if-csv --file example.yml --params cpu/energy --output result.csv`
  AND example contains the following yaml data: 
```yaml
name: basic
description: a minimal manifest executing a single plugin on a single component for a single timestep
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: ['csv']
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30
      outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
          cpu/thermal-design-power: 100
          cpu/energy: 0.000013270071138211382
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30
          cpu/thermal-design-power: 100
          cpu/energy: 0.00001650338753387534

```

  THEN result.csv should contain:
| | | |
|------|-------|-------|
|Path	| 2023-07-06T00:00	| 2023-07-06T01:00 |
|tree.children.child-0.cpu/energy |	0.000013270071138211382	| 0.00001650338753387534 |

- [x] if no output file is defined, pretty print the csv data to the console

  GIVEN the `if-csv` feature is available
  WHEN I run the following command
```
if-csv --file example.yml --params cpu/energy
```
  AND the content of `example.yml` is identical to the previous acceptance criterion
  THEN I should see the following in the console

```sh
["path","2023-07-06T00:00","2023-07-06T01:00"]
"tree.children.child-0.cpu/energy","0.000013270071138211382","0.00001650338753387534 "
```

- [x] `if-csv` should accept output data piped from `ie`
  GIVEN `if-csv` is available
  WHEN I run the following command
```
ie -m example.yml | if-csv --params cpu/energy --output result.csv
```
AND `example.yml` contains

```yaml
name: basic
description: a minimal manifest executing a single plugin on a single component for a single timestep
tags:
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: ['csv']
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T01:00
          duration: 1
          cpu/utilization: 30
```

THEN `result.csv` should contain

| | | |
|------|-------|-------|
|Path	| 2023-07-06T00:00	| 2023-07-06T01:00 |
|tree.children.child-0.cpu/energy |	0.000013270071138211382	| 0.00001650338753387534 |

- [x] `if-csv` is a standard feature of IF, meaning it comes bundled and included in IF's `package.json` the same as `if-diff` and `if-env`

- [x] `if-csv` is included in the CLI reference documentation on if-docs
