### ISSUE TITLE
Update `if-diff` to ignore `outputs` `name` `description` and `tags`

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#792]
**What**
Update matching logic in `if-diff` to ignore the following fields:

```
initialize:
  outputs
```
```
name:
```
```
description:
```
```
tags:
```

**why**
These are not functionally important for output matching. Also, the `outputs` matching logic currently makes piping `ie` outputs into `if-diff` awkward.

**prerequisites**

None

**SoW**
- [ ] Update `if-diff` logic to ignore `outputs`, `name`, `description`, `tags`

**Acceptance criteria**

- [ ] `if-diff` ignores `outputs`, `name`, `description`, `tags`
  GIVEN `if-diff` ignores the specified fields
  WHEN I run `if-diff -s source.yml -t target.yml` with the following manifests:

source.yml:
```yaml
name: source-name
description: source-description
tags: source-tag
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: ['yaml']
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20

``` 

target.yml;

```yaml
source.yml:
```yaml
name: target-name
description: target-description
tags: target-tag
initialize:
  plugins:
    teads-curve: 
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: null
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20

``` 

  THEN the response is

```
Files match!
```
