### ISSUE TITLE
Ensure builtins do not panic when they see zeros

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#850]
**What**

Ensure builtins do not panic when they receive input data with zero values.

**Why**

There are several cases where our builtins panic when they see zeros int he input data, often arising from the input data validation. However, this causes pipeline to break when time sync is executed mid-pipeline, because time-sync can infill unknown values with zeros in some cases. Therefore, we need to ensure builtins handle zeroes more gracefully, in a way that does not break whjen paired with time-sync.

**Context**
We will soon split the IF pipeline into distinct phases and assert that time-sync happ[enes after `regroup` and before `compute`. This will exacerbate the problem that builtins panic when they see zeroes in the input data. We need to ensure the builtins handle this appropriately in advance of the phased execution being implemented.

**Prerequisites/resources**
none

**SoW (scope of work)**
- [x] Sum, Multiply, Subtract allow input arguments to be zero 
  - For sum, these should all be valid calculations: `0 + 1 = 1`, `1 + 0 = 1`, `0 + 0 = 0`
  - For Multiply, these should all be valid computations: `1*1 = 1`, `0 * 1 = 0`, `1 * 0 = 0`, `0 * 0 = 0`
  - For Subtract, these should all be valid calculations: `0 - 1 = -1`, `1 - 0 = 1`, `0 - 0 = 0`
  - For Coefficient. these should all be valid calculations: `1*1 = 1`, `0 * 1 = 0`, `1 * 0 = 0`, `0 * 0 = 0`
  - For Exponent. these should all be valid calculations: `1**1 = 1`, `0 ** 1 = 0`, `1 ** 0 = 1`, `0 ** 0 = 0`
- [x] Divide should *not* allow divide by zero, but it should not panic either.
  - For Divide, these are the correct behaviours: 
    - `0 / 1 = 0`, 
    - `1 / 0 = 1` plus  `WARNING: Division by zero error! No Division applied in inputs[N].key`   
    - `0 / 0 = 0` plus  `WARNING: Division by zero error! No Division applied in inputs[N].key` 
- [x] SCI should also follow the rules for Divide:
  - if functional unit = 0
    -  `0 / functional-unit = 0`, 
    - `1 / functional-unit = 1` plus  `WARNING: Division by zero error! No Division applied in inputs[N].key`   
- [ ] documentation updated
- [x] unit tests updated to cover zero cases

**Acceptance criteria**
- [x] No builtins fail when they encounter zeroes in the input data

  GIVEN the builtins handle zeroes correctly
  WHEN I run `if-run -m zero-manifest.yml -s`
  AND `zero-manifest.yml` contains the following:

```yaml
name: generics
description: a pipeline that does arbitrary calculations using our generic arithmetic builtins
tags:
initialize:
  plugins:
    "sum-zero-and-one":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-plus-zero
    "sum-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-plus-zero
    "subtract-one-and-zero":
      path: "builtin"
      method: Subtract
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-minus-zero
    "subtract-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-minus-zero
    "subtract-zero-and-one":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - some-value
        output-parameter: zero-minus-one
    "coefficient-one-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 1
        output-parameter: zero-times-one-coefficient
    "coefficient-zero-times-one":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: some-value
        coefficient: 0
        output-parameter: one-times-zero-coefficient
    "coefficient-zero-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 0
        output-parameter: zero-times-zero-coefficient
    "multiply-one-times-zero":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["some-value", "zero-value"]
        output-parameter: "one-times-zero"
    "multiply-zero-times-zero":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["zero-value", "zero-value"]
        output-parameter: "zero-times-zero"
    exponent-one-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'some-value'
        exponent: 0
        output-parameter: 'one-raised-to-zero-power'
    exponent-zero-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 0
        output-parameter: 'zero-raised-to-zero-power'
    exponent-zero-to-one:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 1
        output-parameter: 'zero-raised-to-first-power'
    "sci":
      path: "builtin"
      method: Sci
      global-config:
        functional-unit: "zero-value"
tree:
  children:
    child-1:
      pipeline:
        - sum-zero-and-one
        - sum-zero-and-zero
        - subtract-one-and-zero
        - subtract-zero-and-zero
        - subtract-zero-and-one
        - coefficient-one-times-zero
        - coefficient-zero-times-one
        - coefficient-zero-times-zero
        - multiply-one-times-zero
        - multiply-zero-times-one
        - exponent-one-to-zero
        - exponent-zero-to-one
        - exponent-zero-to-zero
        - sci
      config:
      defaults:
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          some-value: 1
          zero-value: 0
```

  THEN the output should look as follows:

```yaml
name: generics
description: a pipeline that does arbitrary calculations using our generic arithmetic builtins
tags:
initialize:
  plugins:
    "sum-zero-and-one":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-plus-zero
    "sum-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-plus-zero
    "subtract-one-and-zero":
      path: "builtin"
      method: Subtract
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-minus-zero
    "subtract-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-minus-zero
    "subtract-zero-and-one":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - some-value
        output-parameter: zero-minus-one
    "coefficient-one-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 1
        output-parameter: zero-times-one-coefficient
    "coefficient-zero-times-one":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: some-value
        coefficient: 0
        output-parameter: one-times-zero-coefficient
    "coefficient-zero-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 0
        output-parameter: zero-times-zero-coefficient
    "multiply-one-times-zero":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["some-value", "zero-value"]
        output-parameter: "one-times-zero"
    "multiply-zero-times-zero":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["zero-value", "zero-value"]
        output-parameter: "zero-times-zero"
    exponent-one-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'some-value'
        exponent: 0
        output-parameter: 'one-raised-to-zero-power'
    exponent-zero-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 0
        output-parameter: 'zero-raised-to-zero-power'
    exponent-zero-to-one:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 1
        output-parameter: 'zero-raised-to-first-power'
    "sci":
      path: "builtin"
      method: Sci
      global-config:
        functional-unit: "zero-value"
tree:
  children:
    child-1:
      pipeline:
        - sum-zero-and-one
        - sum-zero-and-zero
        - subtract-one-and-zero
        - subtract-zero-and-zero
        - subtract-zero-and-one
        - coefficient-one-times-zero
        - coefficient-zero-times-one
        - coefficient-zero-times-zero
        - multiply-one-times-zero
        - multiply-zero-times-one
        - exponent-one-to-zero
        - exponent-zero-to-one
        - exponent-zero-to-zero
        - sci
      config:
      defaults:
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          some-value: 1
          zero-value: 0
      outputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          some-value: 1
          zero-value: 0
          one-plus-zero: 1
          zero-plus-one: 1
          zero-plus-zero: 0
          one-minus-zero: 1
          zero-minus-zero: 0
          zero-minus-one: -1
          zero-times-one-coefficient: 0
          zero-times-zero-coefficient: 0
          one-times-zero-coefficient: 0
          one-times-zero: 0
          zero-times-zero: 0
          one-raised-to-zero-power: 1
          zero-raised-to-zero-power: 0
          zero-raised-to-first-power: 0
          sci: 0
```

- [x] Divide emits a warning when attempting to divide by zero
  When Divide is attempting to divide by zero, it DOES NOT DO THE DIVISION - it emits a warning

```sh
DivisionByZeroError: you are attempting to divide by zero in <plugin> : inputs[n]`
```
  The output value returned depends on the division details:
  - For N * 0, return N
  - For 0 * N, return N
  - For 0 * 0, return 0

- [x] SCI emits a warning when attempting to divide by zero
  When SCI is attempting to divide by zero, it DOES NOT DO THE DIVISION - it emits a warning

```sh
DivisionByZeroError: you are attempting to divide by zero in <plugin> : inputs[n]`
```
  The output value returned depends on the division details:

  - For functional-unit * 0, return 0
  - For N * functional-unit, where functional-unit = 0, return N
  - For functional-unit * 0, where functional-unit = 0, return 0
