### ISSUE TITLE
Add `copy-param` as an IF `builtin`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#853]
**What**
Adds a new `builtin` for copying existing parameters to new keys int he inputs array

**Why**
Useful for renaming parameters, fixes pipelines that replicate the behaviour of e.g. `sci-e` where specific naming patterns were expected but not provided by earlier plugins. Alternative to the `mapping` feature that will come later.

**Context**
This is an easy way to fix pipeline errors where specific parameters are required, in advance of the `mapping` feature that will be implemented in the next sprint. It's worth having both options as the ability to copy parameters and optionally rename is generally useful for other purposes too.

**Prerequisites/resources**
none

**SoW (scope of work)**

- [ ] add builtin for copy-param
- [ ] documentation updated
- [ ] test cases added
- [ ] linked from if-docs

**Acceptance criteria**
- [ ] Copy param copies a given parameter to a new key and optionally deletes the original from the `inputs` array.

GIVEN the builtin is available
WHEN I run `if-run -m copy-yml`
AND `copy.yml` contains

```yml
name: copy-param
description:
tags:
initialize:
  plugins:
    copy-param:
      path: builtin
      method: Copy
      global-config:
        keep-existing: true
        from: original
        to: copy
tree:
  children:
    child-1:
      pipeline:
        - copy-param
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          original: 'hello'

```

THEN the output should be:

```yaml
name: copy-param
description: null
tags: null
initialize:
  plugins:
    copy-param:
      path: builtin
      method: Copy
      global-config:
        keep-existing: true
        from: original
        to: copy
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/index.ts -m manifests/examples/copy.yaml -s
  environment:
    if-version: 0.4.0
    os: linux
    os-version: 5.15.0-107-generic
    node-version: 21.4.0
    date-time: 2024-06-20T13:03:12.427Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-core@0.0.7'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
  status: success
tree:
  children:
    child-1:
      pipeline:
        - copy-param
      inputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          original: hello
      outputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          original: hello
          copy: hello
```
