### ISSUE TITLE
Unhandled error when running manifest with broken syntax

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#858]
## Expected Behaviour
The error should be passed to IF and be handled by it.

## Actual Behaviour
Unhandled exception is thrown. 
error:     can not read an implicit mapping pair; a colon is missed (4:11)

## Steps to Reproduce
1. Run the below attached manifest file 

## Manifest File That Generated the Error
```
name: template manifest # rename me!
description: auto-generated template # update description!
tags: # add any tags that will help you to track your manifests
initialize:
 #outputs:
    #- yaml # you can add - csv to export to csv
  plugins: # add more plugins for your use-case
    memory-energy-from-memory-util: # you can name this any way you like!
      method: Coefficient # the name of the function exported from the plugin
      path: "builtin" # the import path
      global-config: # anmy config required by the plugin
        input-parameter: "memory/utilization"
        coefficient: 0.0001 #kwH/GB
        output-parameter: "memory/energy"
tree:
  children: # add a chile for each distinct component you want to measure
    child:
      pipeline: # the pipeline is an ordered list of plugins you want to execute
        - memory-energy-from-memory-util # must match the name in initialize!
      config: # any plugin specific, node-level config
      inputs:
        - timestamp: 2023-12-12T00:00:00.000Z # ISO 8061 string
          duration: 3600 # units of seconds
          memory/utilization: 10
```

![Image](https://github.com/Green-Software-Foundation/if/assets/109615222/0ffd4038-9f3a-4166-8a6a-6ff687ec90f1)
