### ISSUE TITLE
Need help in understanding error

### ISSUE THREAD

**Issue by adamhafiz427** [Green-Software-Foundation/if#900]
Hello, this is not an actual bug per say, but I need help in understanding this error I get from using the `csv-lookup` plugin

## Description of the Error
I'm trying to get the TDP of azure instances using the CSVLookup plugin. This error is thrown:

> error:     Error happened while parsing given CSV file: https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-azure-instances.csv
> InputValidationError: One or more of the given query parameters are not found in the target CSV file column headers.

## Expected Behaviour
Instance class is taken, the value is looked up upon in the CSV and the corresponding TDP should be returned.

## Actual Behaviour
Error states that query parameters (only the "instance-class" column in the CSV) is not found in the CSV file.
Here is the link to the CSV: https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-azure-instances.csv

## Steps to Reproduce
Run the IF normally with a manifest similar to the one below

## Manifest File That Generated the Error
I can't provide the entire manifest file, but here is the "initialize" part
```
initialize:
  plugins:
    cloud-metadata:
      method: CSVLookup
      path: builtin
      global-config:
        filepath: https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-azure-instances.csv
        query:
          instance-class: cloud/instance-type
        output:
        - cpu-tdp
        - cpu/thermal-design-power
    teads-curve:
      method: TeadsCurve
      path: '@grnsft/if-unofficial-plugins'
    e-mem:
      method: EMem
      path: '@grnsft/if-plugins'
      global-config:
        energy-per-gb: 0.000392
    sci-e:
      method: SciE
      path: '@grnsft/if-plugins'
    sci-m:
      method: SciM
      path: '@grnsft/if-plugins'
    sci-o:
      method: SciO
      path: '@grnsft/if-plugins'
  outputs:
  - yaml
```

And here are the instance-classes of my inputs:
```
Standard_B2as_v2
Standard_B2ms
Standard_D2s_v3
Standard_B1s
Standard_DS2_v2
```
They were all present in the `instance-class` column of the azure instances CSV.

## Runtime Info
package.json: 
`{
  "dependencies": {
    "@grnsft/if": "0.5.0",
    "ts-node": "10.9.1",
    "luxon": "3.4.4"
  }
}`
