### ISSUE TITLE
Create time conversion plugin

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#910]
**What**
Create a plugin that scales given values by the duration of each timestep in the `inputs` array

**Why**
sub of #898 

**Context**

There are cases where we have to do some offline calculations and hardcode them into a manifest,. or use prepublished values that are normalized to some timescale that doesn't map directly to the timescales represented by our input data array, for example we might want to fall back to some regional averages for energy used to light workspaces, or run laptops, and that data is onyl available in kWh/year. We want to be able to pass the value to a plugin, tell the plugin the current value is "per year" and to convert it to "per duration" in each element in the inputs array.

e.g.
if we have timesteps of 10s:

`10kWh/yr --> plugin --> 3.1688e-06 kWh/10s`

It should be able to handle time units grabbed from `duration` OR named time units. For example, if the new time value defined in the config is `duration` then the new time unit should be "quantity per duration-number of seconds", as `duration` is always given in seconds. However, the user should also be able to pass `seconds`, `minutes`, `hours`, `month` etc to convert to common time units.

This can be an IF builtin.

The intiialization for the plugin should look as follows:

```
initialize:
  plugins:
    time-converter:
      method: TimeConverter
      path: builtin
      config:
        input-parameter: 'energy-per-year'
        original-time-unit: 'year'
        new-time-unit: 'duration' 
        output-parameter: 'energy-per-duration'
```

The plugin should then grab the value for `energy-per-year` from each element in the input array and return that input scaled to the `duration` and add it to the array as `energy-per-duration`.

**Prerequisites/resources**
None

**SoW (scope of work)**

- [ ] create IF builtin, `time-conversion` 
- [ ] documentation updated
- [ ] test cases added
- [ ] linked on if-docs/reference/plugins

**Acceptance criteria**

- [ ] plugin converts given value to new time unit defined using `duration`

**Given** the plugin works as intended
**When** (Action): I run the following manifest
```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    time-converter:
      method: TimeConverter
      path: builtin
      config:
        input-parameter: 'energy-per-year'
        original-time-unit: 'year'
        new-time-unit: 'duration' 
        output-parameter: 'energy-per-duration'
tree:
  children:
    child:
      pipeline:
        - time-converter
      config:
      defaults:
        - energy-per-year: 10000
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600

```

**Then** (Assertion): I get the following output:

```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    time-converter:
      method: TimeConverter
      path: builtin
      config:
        input-parameter: 'energy-per-year'
        original-time-unit: 'year'
        new-time-unit: 'duration' 
        output-parameter: 'energy-per-duration'
tree:
  children:
    child:
      pipeline:
        - time-converter
      config:
      defaults:
        - energy-per-year: 10000
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          energy-per-duration: 1.1407711613050422
```

- [ ] plugin converts given value to new time unit defined using `duration`

**Given** the plugin works as intended
**When** (Action): I run the following manifest (with new time expressed as a named unit)

```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    time-converter:
      method: TimeConverter
      path: builtin
      config:
        input-parameter: 'energy-per-year'
        original-time-unit: 'year'
        new-time-unit: 'week' 
        output-parameter: 'energy-per-duration'
tree:
  children:
    child:
      pipeline:
        - time-converter
      config:
      defaults:
        - energy-per-year: 10000
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600

```

**Then** (Assertion): I get the following output:

```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    time-converter:
      method: TimeConverter
      path: builtin
      config:
        input-parameter: 'energy-per-year'
        original-time-unit: 'year'
        new-time-unit: 'duration' 
        output-parameter: 'energy-per-duration'
tree:
  children:
    child:
      pipeline:
        - time-converter
      config:
      defaults:
        - energy-per-year: 10000
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          energy-per-duration: 192.307
```

This should work for the following set of time units:

- [ ] The named time units cover a comprehensive set of cases and is robust to a range of common naming conventions (e.g. `secs, seconds, s, sec` are all understood to mean seconds.

Here's the set of cases that should work and the corresponding number of seconds they represent:

```
  s: 1,
  second: 1,
  sec: 1,
  secs: 1,
  seconds: 1,
  min: 60,
  mins: 60,
  minute: 60,
  minutes: 60,
  h: 3600,
  hs: 3600,
  hr: 3600,
  hrs: 3600,
  hour: 3600,
  hours: 3600,
  d: 86400,
  ds: 86400,
  day: 86400,
  days: 86400,
  w: 604800,
  ws: 604800,
  wk: 604800,
  wks: 604800,
  week: 604800,
  weeks: 604800,
  m: 2419200,
  mnth: 2419200,
  mth: 2419200,
  mnths: 2419200,
  mths: 2419200,
  month: 2419200,
  months: 2419200,
  y: 31536000,
  ys: 31536000,
  yr: 31536000,
  yrs: 31536000,
  year: 31536000,
  years: 31536000,
```
