### ISSUE TITLE
Fix aggregation config 

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#941]
**What**
After the recent refactoring where `aggregation-method` was moved into the `parameter-metadata` we have two conflicting ways to define the aggregation method - it is still an expected field in the to level aggregation config. We need to remove this field from the top level config to unblock the method definition in the metadata.

**Why**
We currently have two conflicting places to define aggregation method.

**Context**
part of parameter metadata upgrade

Currently the aggregation config looks as follows, with `method` being a required field:

```yaml
aggregation:
  metrics:
    "cpu/utilization":
      method: avg
  type: both
```

It should be updated to the following:

```yaml
aggregation:
  metrics: 
    - carbon
    - energy
  type: both
```

**Prerequisites/resources**
n/a

**SoW (scope of work)**
- [ ] update config as described above
- [ ] update manifests that use aggregate feature
- [ ] documentation updated
- [ ] test cases added if necessary

**Acceptance criteria**

**Given** (Setup): The requested changes have been made

**When** (Action): i run the following manifest

```yaml
name: sci
description: successful path
tags:
explainer: true
aggregation:
  metrics: 
    - carbon
  type: both
initialize:
  plugins:
    mock-observations:
      kind: plugin
      method: MockObservations
      path: "builtin"
      global-config:
        timestamp-from: 2023-07-06T00:00
        timestamp-to: 2023-07-06T00:10
        duration: 60
        components:
          - cloud/instance-type: A1
          - cloud/instance-type: B1
        generators:
          common:
            region: uk-west
            # common-key: common-val
          randint:
            carbon:
              min: 1
              max: 50
            requests:
              min: 1
              max: 999
    sci:
      kind: plugin
      method: Sci
      path: "builtin"
      global-config:
        functional-unit: requests
      parameter-metadata:
        inputs:
          carbon:
            description: grams of CO2eq
            unit: gCO2eq
            aggregation-method: sum
          requests:
            description: number of requests made to API
            unit: requests
            aggregation-method: sum
tree:
  children:
    child:
      pipeline:
        observe:
          - mock-observations
        compute:
          - sci
      inputs:

```

**Then** (Assertion): I get the following result

```yaml
name: sci
description: successful path
tags: null
explainer: true
aggregation:
  metrics:
    carbon:
      method: avg
  type: both
initialize:
  plugins:
    mock-observations:
      path: builtin
      method: MockObservations
      global-config:
        timestamp-from: 2023-07-06T00:00
        timestamp-to: 2023-07-06T00:10
        duration: 60
        components:
          - cloud/instance-type: A1
          - cloud/instance-type: B1
        generators:
          common:
            region: uk-west
          randint:
            carbon:
              min: 1
              max: 50
            requests:
              min: 1
              max: 999
    sci:
      path: builtin
      method: Sci
      global-config:
        functional-unit: requests
      parameter-metadata:
        inputs:
          carbon:
            unit: gCO2eq
            description: grams of CO2eq
            aggregation-method: sum
          requests:
            unit: requests
            description: number of requests made to API
            aggregation-method: sum
execution:
  command: >-
    /home/user/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/user/Code/if/src/if-run/index.ts --observe --compute -m
    manifests/examples/demo.yml
  environment:
    if-version: 0.5.0
    os: linux
    os-version: 5.15.0-117-generic
    node-version: 21.4.0
    date-time: 2024-08-06T15:10:59.803Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-core@0.0.16'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - cross-env@7.0.3
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.23.8
  status: success
explain:
  mock-observations:
    method: MockObservations
    path: builtin
    inputs: undefined
    outputs: undefined
tree:
  children:
    child:
      pipeline:
        observe:
          - mock-observations
        compute:
          - sci
      inputs:
        - timestamp: '2023-07-06T00:00:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 47
          requests: 980
        - timestamp: '2023-07-06T00:01:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 47
          requests: 201
        - timestamp: '2023-07-06T00:02:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 2
          requests: 813
        - timestamp: '2023-07-06T00:03:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 34
          requests: 458
        - timestamp: '2023-07-06T00:04:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 31
          requests: 285
        - timestamp: '2023-07-06T00:05:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 13
          requests: 518
        - timestamp: '2023-07-06T00:06:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 2
          requests: 897
        - timestamp: '2023-07-06T00:07:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 22
          requests: 938
        - timestamp: '2023-07-06T00:08:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 1
          requests: 185
        - timestamp: '2023-07-06T00:09:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 45
          requests: 940
        - timestamp: '2023-07-06T00:00:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 6
          requests: 18
        - timestamp: '2023-07-06T00:01:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 19
          requests: 739
        - timestamp: '2023-07-06T00:02:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 32
          requests: 273
        - timestamp: '2023-07-06T00:03:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 18
          requests: 288
        - timestamp: '2023-07-06T00:04:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 8
          requests: 109
        - timestamp: '2023-07-06T00:05:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 35
          requests: 264
        - timestamp: '2023-07-06T00:06:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 1
          requests: 364
        - timestamp: '2023-07-06T00:07:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 13
          requests: 87
        - timestamp: '2023-07-06T00:08:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 16
          requests: 282
        - timestamp: '2023-07-06T00:09:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 8
          requests: 907
      outputs:
        - timestamp: '2023-07-06T00:00:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 47
          requests: 980
          sci: 0.04795918367346939
        - timestamp: '2023-07-06T00:01:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 47
          requests: 201
          sci: 0.23383084577114427
        - timestamp: '2023-07-06T00:02:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 2
          requests: 813
          sci: 0.0024600246002460025
        - timestamp: '2023-07-06T00:03:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 34
          requests: 458
          sci: 0.07423580786026202
        - timestamp: '2023-07-06T00:04:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 31
          requests: 285
          sci: 0.10877192982456141
        - timestamp: '2023-07-06T00:05:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 13
          requests: 518
          sci: 0.025096525096525095
        - timestamp: '2023-07-06T00:06:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 2
          requests: 897
          sci: 0.002229654403567447
        - timestamp: '2023-07-06T00:07:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 22
          requests: 938
          sci: 0.023454157782515993
        - timestamp: '2023-07-06T00:08:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 1
          requests: 185
          sci: 0.005405405405405406
        - timestamp: '2023-07-06T00:09:00.000Z'
          duration: 60
          cloud/instance-type: A1
          region: uk-west
          carbon: 45
          requests: 940
          sci: 0.047872340425531915
        - timestamp: '2023-07-06T00:00:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 6
          requests: 18
          sci: 0.3333333333333333
        - timestamp: '2023-07-06T00:01:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 19
          requests: 739
          sci: 0.02571041948579161
        - timestamp: '2023-07-06T00:02:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 32
          requests: 273
          sci: 0.11721611721611722
        - timestamp: '2023-07-06T00:03:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 18
          requests: 288
          sci: 0.0625
        - timestamp: '2023-07-06T00:04:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 8
          requests: 109
          sci: 0.07339449541284404
        - timestamp: '2023-07-06T00:05:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 35
          requests: 264
          sci: 0.13257575757575757
        - timestamp: '2023-07-06T00:06:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 1
          requests: 364
          sci: 0.0027472527472527475
        - timestamp: '2023-07-06T00:07:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 13
          requests: 87
          sci: 0.14942528735632185
        - timestamp: '2023-07-06T00:08:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 16
          requests: 282
          sci: 0.05673758865248227
        - timestamp: '2023-07-06T00:09:00.000Z'
          duration: 60
          cloud/instance-type: B1
          region: uk-west
          carbon: 8
          requests: 907
          sci: 0.008820286659316428
      aggregated:
        carbon: 400
  outputs:
    - carbon: 47
      timestamp: '2023-07-06T00:00:00.000Z'
      duration: 60
    - carbon: 47
      timestamp: '2023-07-06T00:01:00.000Z'
      duration: 60
    - carbon: 2
      timestamp: '2023-07-06T00:02:00.000Z'
      duration: 60
    - carbon: 34
      timestamp: '2023-07-06T00:03:00.000Z'
      duration: 60
    - carbon: 31
      timestamp: '2023-07-06T00:04:00.000Z'
      duration: 60
    - carbon: 13
      timestamp: '2023-07-06T00:05:00.000Z'
      duration: 60
    - carbon: 2
      timestamp: '2023-07-06T00:06:00.000Z'
      duration: 60
    - carbon: 22
      timestamp: '2023-07-06T00:07:00.000Z'
      duration: 60
    - carbon: 1
      timestamp: '2023-07-06T00:08:00.000Z'
      duration: 60
    - carbon: 45
      timestamp: '2023-07-06T00:09:00.000Z'
      duration: 60
    - carbon: 6
      timestamp: '2023-07-06T00:00:00.000Z'
      duration: 60
    - carbon: 19
      timestamp: '2023-07-06T00:01:00.000Z'
      duration: 60
    - carbon: 32
      timestamp: '2023-07-06T00:02:00.000Z'
      duration: 60
    - carbon: 18
      timestamp: '2023-07-06T00:03:00.000Z'
      duration: 60
    - carbon: 8
      timestamp: '2023-07-06T00:04:00.000Z'
      duration: 60
    - carbon: 35
      timestamp: '2023-07-06T00:05:00.000Z'
      duration: 60
    - carbon: 1
      timestamp: '2023-07-06T00:06:00.000Z'
      duration: 60
    - carbon: 13
      timestamp: '2023-07-06T00:07:00.000Z'
      duration: 60
    - carbon: 16
      timestamp: '2023-07-06T00:08:00.000Z'
      duration: 60
    - carbon: 8
      timestamp: '2023-07-06T00:09:00.000Z'
      duration: 60
  aggregated:
    carbon: 400
```
