### ISSUE TITLE
Create a sample manifest for visualizer development

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#953]
**Why**: Sub of #951 
**What**: Create a manifest file (Focused on SCI) with enough detail to create a basic visualiser 

**Scope of work:**
- [x] It should describe a close-to-real-life project
- [x] It should contain multiple aggregated metrics
- [x] It should contain enough time series data to create a chart
- [x] It should contain information about the plugins used that can be displayed in the info bubbles on hover
- [ ] TBC

**Comment by jmcook1186** [comment]
@zanete I already provided an initial manifest that meets the above criteria. I can also quickly produce more to meet any additional requirements that arise during the development of the ui.

**Comment by zanete** [comment]
@jmcook1186 that's amazing, are you able to also share it in this issue in case we need to refer back to it? 🙏

**Comment by jmcook1186** [comment]
Done

**Comment by jmcook1186** [comment]
```yaml
name: sci
description: demo with two levels of component nesting
tags: null
explainer: true
aggregation:
  metrics:
    - carbon
    - sci
  type: both
initialize:
  plugins:
    mock-observations:
      path: builtin
      method: MockObservations
      global-config:
        timestamp-from: '2023-07-06T00:00:00'
        timestamp-to: '2023-07-06T00:00:10'
        duration: 5
        components:
          - cloud/instance-type: A1
          - cloud/instance-type: B1
        generators:
          common:
            region: uk-west
          randint:
            carbon:
              min: 1
              max: 50
            users:
              min: 1
              max: 999
    sci:
      path: builtin
      method: Sci
      global-config:
        functional-unit: users
      parameter-metadata:
        inputs:
          carbon:
            unit: gCO2eq
            description: grams of CO2eq
            aggregation-method: sum
          requests:
            unit: user
            description: number of requests made to API
            aggregation-method: avg
        outputs:
          sci:
            unit: gCO2eq/user
            description: grams of CO2eq
            aggregation-method: sum
execution:
  command: >-
    /home/joe/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/joe/Code/if/src/if-run/index.ts -m manifests/examples/demo.yml -o
    manifests/examples/demo-output.yml
  environment:
    if-version: 0.5.0
    os: linux
    os-version: 5.15.0-117-generic
    node-version: 21.4.0
    date-time: 2024-08-08T15:36:13.943Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-core@0.0.16'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - cross-env@7.0.3
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.23.8
  status: success
explain:
  mock-observations:
    method: MockObservations
    path: builtin
    inputs: undefined
    outputs: undefined
tree:
  children:
    component-1:
      pipeline:
        observe:
          - mock-observations
        regroup:
          - cloud/instance-type
          - region
        compute:
          - sci
      children:
        A1:
          children:
            uk-west:
              inputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 22
                  users: 99
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 2
                  users: 706
              outputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 22
                  users: 99
                  sci: 0.2222222222222222
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 2
                  users: 706
                  sci: 0.0028328611898017
              aggregated:
                carbon: 24
                sci: 0.2250550834120239
          outputs:
            - carbon: 22
              sci: 0.2222222222222222
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 2
              sci: 0.0028328611898017
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 24
            sci: 0.2250550834120239
        B1:
          children:
            uk-west:
              inputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 19
                  users: 397
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 31
                  users: 755
              outputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 19
                  users: 397
                  sci: 0.04785894206549118
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 31
                  users: 755
                  sci: 0.04105960264900662
              aggregated:
                carbon: 50
                sci: 0.08891854471449781
          outputs:
            - carbon: 19
              sci: 0.04785894206549118
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 31
              sci: 0.04105960264900662
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 50
            sci: 0.08891854471449781
      outputs:
        - carbon: 41
          sci: 0.2700811642877134
          timestamp: '2023-07-06T00:00:00.000Z'
          duration: 5
        - carbon: 33
          sci: 0.04389246383880832
          timestamp: '2023-07-06T00:00:05.000Z'
          duration: 5
      aggregated:
        carbon: 74
        sci: 0.31397362812652174
    component-2:
      pipeline:
        observe:
          - mock-observations
        regroup:
          - cloud/instance-type
          - region
        compute:
          - sci
      children:
        A1:
          children:
            uk-west:
              inputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 46
                  users: 235
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 30
                  users: 774
              outputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 46
                  users: 235
                  sci: 0.19574468085106383
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: A1
                  region: uk-west
                  carbon: 30
                  users: 774
                  sci: 0.03875968992248062
              aggregated:
                carbon: 76
                sci: 0.23450437077354447
          outputs:
            - carbon: 46
              sci: 0.19574468085106383
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 30
              sci: 0.03875968992248062
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 76
            sci: 0.23450437077354447
        B1:
          children:
            uk-west:
              inputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 41
                  users: 485
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 2
                  users: 564
              outputs:
                - timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 41
                  users: 485
                  sci: 0.08453608247422681
                - timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
                  cloud/instance-type: B1
                  region: uk-west
                  carbon: 2
                  users: 564
                  sci: 0.0035460992907801418
              aggregated:
                carbon: 43
                sci: 0.08808218176500696
          outputs:
            - carbon: 41
              sci: 0.08453608247422681
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 2
              sci: 0.0035460992907801418
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 43
            sci: 0.08808218176500696
      outputs:
        - carbon: 87
          sci: 0.2802807633252906
          timestamp: '2023-07-06T00:00:00.000Z'
          duration: 5
        - carbon: 32
          sci: 0.04230578921326076
          timestamp: '2023-07-06T00:00:05.000Z'
          duration: 5
      aggregated:
        carbon: 119
        sci: 0.3225865525385514
    component-3:
      children:
        component-3-1:
          pipeline:
            observe:
              - mock-observations
            regroup:
              - cloud/instance-type
              - region
            compute:
              - sci
          children:
            A1:
              children:
                uk-west:
                  inputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 45
                      users: 597
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 40
                      users: 47
                  outputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 45
                      users: 597
                      sci: 0.07537688442211055
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 40
                      users: 47
                      sci: 0.851063829787234
                  aggregated:
                    carbon: 85
                    sci: 0.9264407142093446
              outputs:
                - carbon: 45
                  sci: 0.07537688442211055
                  timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                - carbon: 40
                  sci: 0.851063829787234
                  timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
              aggregated:
                carbon: 85
                sci: 0.9264407142093446
            B1:
              children:
                uk-west:
                  inputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 25
                      users: 551
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 11
                      users: 508
                  outputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 25
                      users: 551
                      sci: 0.045372050816696916
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 11
                      users: 508
                      sci: 0.021653543307086614
                  aggregated:
                    carbon: 36
                    sci: 0.06702559412378353
              outputs:
                - carbon: 25
                  sci: 0.045372050816696916
                  timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                - carbon: 11
                  sci: 0.021653543307086614
                  timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
              aggregated:
                carbon: 36
                sci: 0.06702559412378353
          outputs:
            - carbon: 70
              sci: 0.12074893523880746
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 51
              sci: 0.8727173730943206
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 121
            sci: 0.9934663083331281
        component-3-2:
          pipeline:
            observe:
              - mock-observations
            regroup:
              - cloud/instance-type
              - region
            compute:
              - sci
          children:
            A1:
              children:
                uk-west:
                  inputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 36
                      users: 286
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 1
                      users: 275
                  outputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 36
                      users: 286
                      sci: 0.1258741258741259
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: A1
                      region: uk-west
                      carbon: 1
                      users: 275
                      sci: 0.0036363636363636364
                  aggregated:
                    carbon: 37
                    sci: 0.12951048951048952
              outputs:
                - carbon: 36
                  sci: 0.1258741258741259
                  timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                - carbon: 1
                  sci: 0.0036363636363636364
                  timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
              aggregated:
                carbon: 37
                sci: 0.12951048951048952
            B1:
              children:
                uk-west:
                  inputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 28
                      users: 445
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 35
                      users: 480
                  outputs:
                    - timestamp: '2023-07-06T00:00:00.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 28
                      users: 445
                      sci: 0.06292134831460675
                    - timestamp: '2023-07-06T00:00:05.000Z'
                      duration: 5
                      cloud/instance-type: B1
                      region: uk-west
                      carbon: 35
                      users: 480
                      sci: 0.07291666666666667
                  aggregated:
                    carbon: 63
                    sci: 0.1358380149812734
              outputs:
                - carbon: 28
                  sci: 0.06292134831460675
                  timestamp: '2023-07-06T00:00:00.000Z'
                  duration: 5
                - carbon: 35
                  sci: 0.07291666666666667
                  timestamp: '2023-07-06T00:00:05.000Z'
                  duration: 5
              aggregated:
                carbon: 63
                sci: 0.1358380149812734
          outputs:
            - carbon: 64
              sci: 0.18879547418873263
              timestamp: '2023-07-06T00:00:00.000Z'
              duration: 5
            - carbon: 36
              sci: 0.0765530303030303
              timestamp: '2023-07-06T00:00:05.000Z'
              duration: 5
          aggregated:
            carbon: 100
            sci: 0.26534850449176295
      outputs:
        - carbon: 134
          sci: 0.3095444094275401
          timestamp: '2023-07-06T00:00:00.000Z'
          duration: 5
        - carbon: 87
          sci: 0.9492704033973509
          timestamp: '2023-07-06T00:00:05.000Z'
          duration: 5
      aggregated:
        carbon: 221
        sci: 1.258814812824891
  outputs:
    - carbon: 262
      sci: 0.8599063370405442
      timestamp: '2023-07-06T00:00:00.000Z'
      duration: 5
    - carbon: 152
      sci: 1.03546865644942
      timestamp: '2023-07-06T00:00:05.000Z'
      duration: 5
  aggregated:
    carbon: 414
    sci: 1.8953749934899642
```
