### ISSUE TITLE
`copy-param` only works when values are strings

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#964]
## Description of the Error
Invoking the copy-param builtin only works when the value being passed in to the `from` parameter is a string. It should work for any type being passed in.

## Expected Behaviour

When we initialize the following plugin and run it with `size = 34566` in the input data array, it should add `if-repo-size: 34566` to the output array and delete `size: 34566` from the output array.

```yaml
  copy-param-if-repo-size:
    path: builtin
    method: Copy
    global-config:
      keep-existing: false
      from: "size"
      to: "if-repo-size"
```

## Actual Behaviour
We get the following error:

```
[2024-08-13 10:35:24.387 AM] error:     "size" parameter is expected string, received number. Error code: invalid_type.
InputValidationError:   "size" parameter is expected string, received number. Error code: invalid_type.
```

## Steps to Reproduce
- install latest IF
- run the following manifest
- 
```yaml
name: if-sci
description:
tags:
initialize:
  plugins:
    # unit conversions
    duration-in-hours:
      method: Divide
      path: "builtin"
      global-config:
        numerator: duration
        denominator: 3600 # s to hr
        output: duration-in-hours
    ## Github storage for IF
    storage-and-traffic-from-github-if:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if
        time: 'month' # api can only serve within past 4 weeks
    copy-param-if-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "size"
        to: "if-repo-size"
    copy-param-if-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "clones"
        to: "if-repo-clones"
    storage-in-gb-to-tb-if:
      method: Coefficient
      path: builtin
      global-config:
        input-parameters: "if-repo-size" # size comes from github api and represents repo size in gb
        coefficient: 0.001 # convert size to tb
        output-parameter: "storage-tb-if"
    storage-energy-in-watts-if:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if", "watts-per-tb"]
        output-parameter: "storage-watts-if"
    storage-energy-in-wh-if:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if", "duration-in-hours"]
        output-parameter: "storage-wh-if"
    storage-energy-to-kwh-if:
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if
        coefficient: 0.001
        output-parameter: storage-kwh-if
    ## Github storage for if-data
    storage-and-traffic-from-github-if-data:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if-data
        time: 'month' # api can only serve within past 4 weeks
    copy-param-if-data-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "size"
        to: "repo-size-if-data"
    copy-param-if-data-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "clones"
        to: "repo-clones-if-data"
    storage-in-gb-to-tb-if-data:
      method: Coefficient
      path: builtin
      global-config:
        input-parameters: "repo-size-if-data" # size comes from github api and represents repo size in gb
        coefficient: 0.001 # convert size to tb
        output-parameter: "storage-tb-if-data"
    storage-energy-in-watts-if-data:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if-data", "watts-per-tb"]
        output-parameter: "storage-watts-if-data"
    storage-energy-in-wh-if-data:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if-data", "duration-in-hours"]
        output-parameter: "storage-wh-if-data"
    storage-energy-to-kwh-data:
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if-data
        coefficient: 0.001
        output-parameter: storage-kwh-if-data
    ## Github storage for if-docs
    storage-and-traffic-from-github-if-docs:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if-docs
        time: 'month' # api can only serve within past 4 weeks
    copy-param-if-docs-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "size"
        to: "repo-size-if-docs"
    copy-param-if-docs-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: "clones"
        to: "repo-clones-if-docs"
    storage-in-gb-to-tb-if-docs:
      method: Coefficient
      path: builtin
      global-config:
        input-parameters: "size" # size comes from github api and represents repo size in gb
        coefficient: 0.001 # convert size to tb
        output-parameter: "storage-tb-if-docs"
    storage-energy-in-watts-if-docs:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if-docs", "watts-per-tb"]
        output-parameter: "storage-watts-if-docs"
    storage-energy-in-wh-if-docs:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if-docs", "duration-in-hours"]
        output-parameter: "storage-wh-if-docs"
    storage-energy-to-kwh-if-docs:
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if-docs
        coefficient: 0.001
        output-parameter: storage-kwh-if-docs
    # sum storage components and convert to carbon
    sum-storage-energy-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['storage-kwh-if','storage-kwh-if-data', 'storage-kwh-if-docs']
        output-parameter: 'storage-energy'
    # data downloaded from if repositories
    total-data-downloaded-from-if-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if", "repo-clones-if"]
        output-parameter: "data-egress-if" # data transferred in GB
    total-data-downloaded-from-if-docs-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if-docs", "repo-clones-if-docs"]
        output-parameter: "data-egress-if-docs" # data transferred in GB
    total-data-downloaded-from-if-data-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if-data", "repo-clones-if-data"]
        output-parameter: "data-egress-if-data" # data transferred in GB
    # sum storage components and convert to energy
    sum-repo-download-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['data-egress-if','data-egress-if-docs', 'data-egress-if-data']
        output-parameter: 'total-data-egress'
    repo-downloads-to-energy:
      method: Coefficient
      path: 'builtin'
      global-config:
        input-parameter: total-data-egress
        coefficient: 0.001 # from https://www.cloudcarbonfootprint.org/docs/methodology/#networking
        output-parameter: networking-kwh
    # sum energy components and convert to carbon
    sum-energy-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['storage-kwh','networking-kwh']
        output-parameter: 'energy'
    energy-to-carbon:
      method: Multiply
      path: "builtin"
      global-config:
        input-parameters: ["energy", "grid-intensity"]
        output-parameter: "carbon"
tree:
  children:
    if:
      pipeline:
        compute:
          - duration-in-hours
          - storage-and-traffic-from-github-if
          - copy-param-if-repo-size
          - copy-param-if-clones
          - storage-in-gb-to-tb-if
          - storage-energy-in-watts-if
          - storage-energy-in-wh-if
          - storage-energy-to-kwh-if
          - storage-and-traffic-from-github-if-data
          - copy-param-if-data-repo-size
          - copy-param-if-data-clones
          - storage-in-gb-to-tb-if-data
          - storage-energy-in-watts-if-data
          - storage-energy-in-wh-if-data
          - storage-energy-to-kwh-if-data
          - storage-and-traffic-from-github-if-docs
          - copy-param-if-docs-repo-size
          - copy-param-if-docs-clones
          - storage-in-gb-to-tb-if-docs
          - storage-energy-in-watts-if-docs
          - storage-energy-in-wh-if-docs
          - storage-energy-to-kwh-if-docs
          - sum-storage-energy-components
          - total-data-downloaded-from-if-repo
          - total-data-downloaded-from-if-docs-repo
          - total-data-downloaded-from-if-data-repo
          - sum-repo-download-components
          - repo-downloads-to-energy
          - sum-energy-components
          - energy-to-carbon
      defaults:
        watts-per-tb: 0.65 # https://www.cloudcarbonfootprint.org/docs/methodology/#storage
        grid-intensity: 765.49 # US average
      inputs:
        - timestamp: '2024-07-05T13:45:48.398Z'
          duration: 3600
```

## Link to online environment
n/a
 

## Manifest File That Generated the Error

see above

## Links to Any Additional Code
n/a

## Runtime Info
Linux (ubuntu 20.04) 
Node v21.4.0
