### ISSUE TITLE
Create output renaming method that generalizes to any plugin

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#966]
**What**
Add some logic to IF that enables a user to override the name of outputs from a plugin instance using some initilize config.

**Why**
to avoid having to use `copy-param` lots of times in a pipeline to avoid naming collisions

**Context**

During building the IF SCI manifest, a major friction was having to create lots of instances of `copy-param` to rename outputs at the right moment in a pipeline to avoid naming collisions where multiple instances of the same plugin are used and the output name is hardcoded. For example, two instances of the github plugin would both return `size` and `clones`, so we need a way to distinguish them so the second instance does not override the first - e.g. output them as `size-1`, `clones-1` and `size-2` ,`clones-2`.  This should be configurable in each plugin's initialize block and not requiring additional plugins.

Something like this would work well:

```
  example-plugin:
    method: Some
    path: "builtin"
    global-config:
      input: something
    rename-outputs:
      old-name-1: new-name-1
      old-name-2: new-name-2
```

If an output is not included in the `rename-outputs` config block then it gets added using its default name (it still gets created, but no renaming is applied). 

If any unknown value is provided to `rename-outputs`, we just skip it and log a warning.

It's important that this piece of config can be applied to *any* plugin - i.e. this is handled by IF, not in any individual plugin's source code.

**Prerequisites/resources**
n/a

**SoW (scope of work)**

- [ ] feature is added to IF source code
- [ ] documentation updated
- [ ] test cases added

**Acceptance criteria**

GIVEN: the renaming feature is available
WHEN I run the following manifest:

```yaml
name: renaming-demo
description: successful path
tags:
initialize:
  plugins:
    storage-and-traffic-from-github-if:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if
      rename-outputs:
        size: if-repo-size
        clones: if-repo-clones
tree:
  children:
    child:
      pipeline:
        compute:
          - storage-and-traffic-from-github-if
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
```

THEN I should get the following result (these are dummy values). Notice that the default output names are not presented anywhere, instead we only see the new names defined in the `rename-outputs` config:

```yaml
name: renaming-demo
description: successful path
tags:
initialize:
  plugins:
    storage-and-traffic-from-github-if:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if
      rename-outputs:
        size: if-repo-size
        clones: if-repo-clones
tree:
  children:
    child:
      pipeline:
        compute:
          - storage-and-traffic-from-github-if
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          if-repo-size: 364
          if-repo-clones: 6
```
