### ISSUE TITLE
Make "inline" arithmetic work in manifests

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#970]
**What**

Where a number is passed in a manifest, a sum should also work, e.g.

The following should be allowed:

```yaml
some-param: 30*2
duration: 60*60*24*7*4
```

and also the following, using other parameters in the manifest:

```yaml
some-param: other-param*3
```

**Why**

This reduces the number of plugins required in pipelines because simple conversions that would otherwise need dedicated instances of our generic builtins can be done inline. 

**Context**

Part of UX improvements

**Prerequisites/resources**
n/a

**SoW (scope of work)**
- [x] make necessary updates to IF and builtin code 
- [ ] documentation updated
- [x] test cases added
- [ ] add guidance to plugin builder docs to help plugin builders enable this new feature

**Acceptance criteria**

**Given** (Setup): Inline arithmetic is enabled for manifests

**When** (Action): I run the following manifest

```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    coefficient:
      method: Coefficient
      path: "builtin"
      global-config:
        input-parameter: carbon * 3
        coefficient: 3*arbitrary-constant
        output-parameter: "carbon-product"
tree:
  children:
    child:
      pipeline:
        compute:
          - coefficient
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          carbon: 3
          arbitrary-constant: 2

```

**Then** (Assertion): I get the following output:

```yaml
name: coefficient-demo
description: successful path
tags:
initialize:
  plugins:
    coefficient:
      method: Coefficient
      path: "builtin"
      global-config:
        input-parameter: carbon * 3
        coefficient: 3*arbitrary-constant
        output-parameter: "carbon-product"
tree:
  children:
    child:
      pipeline:
        compute:
          - coefficient
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          carbon: 3
          arbitrary-constant: 2
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          carbon: 3
          arbitrary-constant: 2
          carbon-product: 54 // because we are doing (3 * 3) * (3 + 2) 

```
